await page.setViewportSize({width:1440,height:1000});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.dataset.ready==='true');
await page.getByRole('button',{name:'全部折叠',exact:true}).click();
assert.equal(await page.locator('.parameter-group[open]').count(),0);
await page.getByRole('button',{name:'全部展开',exact:true}).click();
assert.equal(await page.locator('.parameter-group[open]').count(),7);
const energy=page.getByRole('spinbutton',{name:'全光斑能量 · Tx前',exact:true});
await energy.fill('24');await energy.press('Tab');await expect(page.locator('#staleBanner')).toBeVisible();
const fixedMetrics=await page.locator('#metrics').innerText();
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.dataset.ready==='true');
await expect(page.getByRole('spinbutton',{name:'全光斑能量 · Tx前',exact:true})).toHaveValue('24');
assert.equal(await page.locator('#metrics').innerText(),fixedMetrics);
await page.getByRole('button',{name:'恢复样例',exact:true}).click();await expect(page.locator('#staleBanner')).toBeHidden();
await page.getByRole('button',{name:'全部折叠',exact:true}).click();
await page.locator('[data-group="tx"]>summary').click();
await page.locator('[data-group="tx"] .subdetails>summary').click();
await expect(page.getByRole('spinbutton',{name:'构造 Tx 角域 H 最小值',exact:true})).toBeVisible();
await page.locator('#channelInput').fill('0,2,4-5');await page.getByRole('button',{name:'应用',exact:true}).click();
assert.equal(await page.locator('.hist-plot').count(),4);
await page.locator('#channelInput').fill('999');await page.getByRole('button',{name:'应用',exact:true}).click();await expect(page.locator('#histError')).toBeVisible();
await page.locator('#channelInput').fill('0,1');await page.getByRole('button',{name:'应用',exact:true}).click();await expect(page.locator('#histError')).toBeHidden();
await page.locator('#timeMin').fill('661');await page.locator('#timeMax').fill('673');await page.getByRole('button',{name:'缩放',exact:true}).click();
await page.locator('[data-series="error"]').uncheck();await page.locator('[data-series="error"]').check();
await page.getByLabel('角度H索引',{exact:true}).selectOption('0');await page.getByLabel('角度V索引',{exact:true}).selectOption('0');
const corner=await page.locator('#captureValue').innerText();await expect(page.locator('#angleLabel')).toContainText('H[0]');
await page.getByRole('button',{name:'选择角度 H 8 V 4',exact:true}).click();
const center=await page.locator('#captureValue').innerText();assert.notEqual(corner,center);
await page.getByRole('button',{name:/任务记录/}).click();await expect(page.locator('#jobHistory')).toBeVisible();await page.getByRole('button',{name:/任务记录/}).click();
await page.getByRole('button',{name:/运行仿真/}).click();await expect(page.locator('#previewDialog')).toBeVisible();await page.getByRole('button',{name:'知道了',exact:true}).click();
await page.locator('#histogramPanel').scrollIntoViewIfNeeded();
const shot=await page.screenshot({fullPage:false});
return {errors,groups:7,persistence:true,channelValidation:true,range:[661,673],corner,center,overflow:await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),screenshot:shot};