await page.setViewportSize({width:1536,height:1160});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8016/system?job=8791dc5875ec4086a52b8aa66871e17f',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.dataset.ready==='true');await expect(page.locator('#bMechanismPanel .ba-stat')).toContainText('未保存');
await page.waitForFunction(()=>document.querySelector('.hist-plot[data-scope="slot"]'));await expect(page.locator('[data-series="error"]')).toBeDisabled();
const legacy=await context.newPage();try{await legacy.goto('http://127.0.0.1:8016/system/scan/legacy',{waitUntil:'networkidle'});await legacy.waitForFunction(()=>document.body.dataset.ready==='true');await expect(legacy.locator('#overviewTabs')).toBeHidden();await expect(legacy.locator('#bHistogramControls')).toBeHidden();assert.equal(await legacy.locator('#channelInput').count(),1);}finally{await legacy.close();}
const prototype=await context.newPage();try{await prototype.goto('http://127.0.0.1:8016/static/prototypes/slot-readout/index.html',{waitUntil:'networkidle'});await prototype.waitForFunction(()=>document.body.dataset.ready==='true');await expect(prototype.locator('.repeat-explanation')).toContainText('N＝3，M＝5');await expect(prototype.locator('.repeat-explanation')).toContainText('不把这5份相加');}finally{await prototype.close();}
await page.goto('http://127.0.0.1:8016/system?job=bb0ed04dd00f485b9c16856d7faa3d67',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.dataset.ready==='true');await expect(page.locator('#bScopeRules')).toContainText('N=10');await expect(page.locator('#bScopeRules')).toContainText('M=10');
await page.locator('#channelInput').fill('3,4');await page.locator('#applyChannels').click();await page.waitForFunction(()=>document.querySelectorAll('.hist-plot[data-scope="slot"]').length===2);
await page.locator('#replayBin').fill('0');await page.locator('#replayRecords').click();await expect(page.locator('#replayState')).toHaveText('分箱未更新。');await expect(page.locator('#histError')).toBeVisible();
await page.locator('#replayBin').fill('1000');await page.locator('#replayRecords').click();await expect(page.locator('#replayState')).toContainText('已按当前采集范围重放');
await page.locator('#bHistogramControls [data-scope]').selectOption('gate');await page.waitForFunction(()=>document.querySelectorAll('.hist-plot[data-scope="gate"]').length===2);await page.locator('#bHistogramControls [data-gate]').fill('9');await page.locator('#bHistogramControls [data-apply]').click();await expect(page.locator('#bHistogramControls [data-badge]')).toHaveText('单 gate · G9 的实际记录');
await page.locator('#histogramPlots').scrollIntoViewIfNeeded();await page.evaluate(()=>scrollTo(0,document.querySelector('#bHistogramControls').getBoundingClientRect().top+scrollY-12));
await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(errors.length,0,errors.join('\n'));const screenshot=await page.screenshot({fullPage:false});
await page.locator('#bHistogramControls [data-scope]').selectOption('slot');await page.waitForFunction(()=>document.querySelectorAll('.hist-plot[data-scope="slot"]').length===2);await page.evaluate(()=>scrollTo(0,0));
return {errors,historicalMUnknown:true,legacyReady:true,prototypeUpdated:true,screenshot};