await page.setViewportSize({width:1720,height:1140});
globalThis.shapeErrors=[];page.on('pageerror',e=>globalThis.shapeErrors.push(e.message));
await page.goto('http://127.0.0.1:8016/system?job=90e9141e1ad34cf3b21a693788a1de41',{waitUntil:'domcontentloaded'});
await expect(page.locator('#resultViewState')).toContainText('90e9141e1ad34cf3b21a693788a1de41',{timeout:30000});
await expect(page.locator('[data-path="optics.psf_sigma_h_um"]')).toHaveValue('8');
await expect(page.locator('[data-path="optics.psf_sigma_v_um"]')).toHaveValue('8');
const rx=page.locator('[data-group="rx"]');if(!await rx.evaluate(e=>e.open))await rx.locator(':scope > summary').click();
await page.locator('[data-path="optics.rx_model"]').selectOption('super_gaussian_psf');
await page.locator('[data-path="optics.psf_sigma_h_um"]').fill('4');
await page.locator('[data-path="optics.psf_sigma_v_um"]').fill('10');
await page.locator('[data-path="optics.psf_order_h"]').fill('2');
await page.locator('[data-path="optics.psf_order_v"]').fill('4');
await page.locator('[data-path="optics.psf_order_v"]').press('Tab');
const tx=page.locator('[data-group="tx"]');if(!await tx.evaluate(e=>e.open))await tx.locator(':scope > summary').click();
await page.locator('[data-path="optics.tx_model"]').selectOption('super_gaussian');
await page.waitForFunction(()=>previewData?.form_configuration.optics.rx_model==='super_gaussian_psf'&&previewData?.form_configuration.optics.psf_sigma_h_um===4&&previewData?.form_configuration.optics.psf_order_v===4&&previewData?.form_configuration.optics.tx_model==='super_gaussian',null,{timeout:30000});
const p=page.locator('#parameterVizDetails');if(!await p.evaluate(e=>e.open))await p.locator('summary').click();
await page.getByRole('tab',{name:'PSF 剖面',exact:true}).click();
await expect(page.locator('#parameterHeatmap .channel-frame')).toHaveCount(0);
await expect(page.locator('#parameterHeatmap .channel-label')).toHaveCount(0);
await expect(page.locator('#parameterVizContent')).toContainText('H / x · 圆点虚线');
await expect(page.locator('#parameterVizContent')).toContainText('V / y · 菱点虚线');
globalThis.shapesPreview=await page.evaluate(()=>({sigmaH:previewData.form_configuration.optics.psf_sigma_h_um,sigmaV:previewData.form_configuration.optics.psf_sigma_v_um,tx:previewData.form_configuration.optics.tx_model,rx:previewData.form_configuration.optics.rx_model,curve:previewData.parameter_figures.psf,normalization:previewData.optics.tx_energy_normalization}));
await page.locator('#parameterVizPanel').scrollIntoViewIfNeeded();
await rx.locator('.axis-pairs:visible').first().scrollIntoViewIfNeeded();
return await page.screenshot({fullPage:false});
