await page.setViewportSize({width:1536,height:1180});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8016/static/prototypes/b-channel-layout/index.html',{waitUntil:'networkidle'});
await page.waitForFunction(()=>document.body.dataset.ready==='true');
assert.equal(await page.locator('[data-map-channel]').count(),8);
assert.equal(await page.locator('[data-hist-card]').count(),2);
await page.locator('#channelInput').fill('1, 3-4');
await page.locator('#applyChannels').click();
assert.equal(await page.locator('[data-map-channel].selected').count(),3);
assert.equal(await page.locator('[data-hist-card="3"]').count(),1);
await page.locator('[data-map-channel="7"]').click();
assert.equal(await page.locator('[data-picker-channel="7"]').getAttribute('aria-pressed'),'true');
assert.equal(await page.locator('[data-hist-card="7"]').count(),1);
await page.locator('[data-map-channel="0"]').focus();
await page.keyboard.press('Enter');
assert.equal(await page.locator('[data-picker-channel="0"]').getAttribute('aria-pressed'),'true');
await page.locator('#channelInput').fill('8');await page.locator('#applyChannels').click();
await expect(page.locator('#selectionError')).toBeVisible();
await page.locator('#channelInput').fill('0,4');await page.locator('#applyChannels').click();
await page.locator('#timeMin').fill('980');await page.locator('#timeMax').fill('990');await page.locator('#applyWindow').click();
await expect(page.locator('#timeError')).toBeHidden();
await page.locator('#spotOpacity').focus();await page.keyboard.press('Home');
assert.equal(await page.locator('#spotLayer').getAttribute('opacity'),'0');
await page.keyboard.press('End');assert.equal(await page.locator('#spotLayer').getAttribute('opacity'),'1');
await page.keyboard.press('ArrowLeft');
await page.locator('#spotVisible').uncheck();assert.equal(await page.locator('#spotLayer').getAttribute('opacity'),'0');
await page.locator('#spotVisible').check();
await page.locator('#spotOpacity').evaluate(el=>{el.value='55';el.dispatchEvent(new Event('input',{bubbles:true}));});
await page.locator('#pixelGrid').uncheck();assert.equal(await page.locator('#pixelLayer').evaluate(el=>getComputedStyle(el).display),'none');await page.locator('#pixelGrid').check();
await page.locator('#focusEcho').click();
await page.evaluate(()=>scrollTo(0,0));
assert.equal(errors.length,0,errors.join('\n'));
const info=await page.evaluate(()=>({metrics:document.querySelector('#layoutMetrics').innerText,selection:document.querySelector('#channelInput').value,mapSelection:[...document.querySelectorAll('[data-map-channel].selected')].map(el=>el.dataset.mapChannel),overflow:document.documentElement.scrollWidth>innerWidth}));
return {info,errors,screenshot:await page.screenshot({fullPage:false})};