globalThis.finalScanErrors=[];page.on('pageerror',e=>globalThis.finalScanErrors.push(e.message));
await page.setViewportSize({width:1440,height:1050});
await page.goto('http://127.0.0.1:8015/system',{waitUntil:'networkidle'});
await page.getByRole('button',{name:'恢复默认',exact:true}).click();
await expect(page.getByRole('button',{name:'恢复默认',exact:true})).toBeEnabled();
await page.locator('[data-path="optics.range_m"]').fill('75');
await page.getByRole('button',{name:'用当前B参数新建扫描配置',exact:true}).click();
await expect(page).toHaveURL(/\/system\/scan$/);
await expect(page.locator('[data-path="optics.range_m"]')).toHaveValue('75');
assert.equal(await page.locator('[data-path="timing.laser_shots"]').count(),0);
await expect(page.locator('#formStatus')).toContainText('重新决定');
await page.getByRole('button',{name:'恢复默认',exact:true}).click();
await expect(page.getByRole('button',{name:'恢复默认',exact:true})).toBeEnabled();
await page.locator('[data-path="scan.encoder_latency_ns"]').fill('50000');
await page.getByRole('button',{name:'预览轨迹与发数',exact:true}).click();
await expect(page.locator('#scanViewStatus')).toContainText('仅预览时序');
await page.getByRole('button',{name:'恢复默认',exact:true}).click();
await expect(page.getByRole('button',{name:'恢复默认',exact:true})).toBeEnabled();
const accepted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
await page.getByRole('button',{name:'提交仿真',exact:true}).click();const job=await (await accepted).json();
await expect(page.locator('#resultStatus')).toContainText('C_pulse_resolved_scan',{timeout:30000});
await page.locator('#scanReplayBin').fill('2000');await page.getByRole('button',{name:'重放扫描重建',exact:true}).click();
await expect(page.locator('#scanViewStatus')).toContainText('未重新采样');
const download=await tabbit.triggerAndWait('download',()=>page.getByRole('button',{name:'导出 XYZ 点云 CSV',exact:true}).click());
const csv=await (await context.request.get('http://127.0.0.1:8015/api/jobs/'+job.id+'/point-cloud.csv?bin_ps=2000')).text();
const csvRows=csv.trim().split(/\r?\n/);assert(csvRows[0].endsWith('processing_bin_ps'));assert(csvRows[1].endsWith(',2000.0')||csvRows[1].endsWith(',2000'));
await page.goto('http://127.0.0.1:8015/system/scan?job='+job.id,{waitUntil:'networkidle'});
await expect(page.locator('#formStatus')).toContainText('参数快照');
await expect(page.locator('#error')).toBeHidden();
await expect(page.locator('.katex-error')).toHaveCount(0);
await page.locator('#scanPanel').scrollIntoViewIfNeeded();
return {job:job.id,reviewUrl:page.url(),errors:globalThis.finalScanErrors,download:download.suggestedFilename(),csvPoints:csvRows.length-1,katexCount:await page.locator('#opticalResults .katex').count(),screenshot:await page.screenshot({fullPage:false})};
