const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.setViewportSize({width:1536,height:1100});
await page.goto('http://127.0.0.1:8016/static/prototypes/c-exposure/index.html',{waitUntil:'networkidle'});
await page.waitForFunction(()=>document.body.dataset.ready==='true');
await page.getByRole('button',{name:'全部折叠',exact:true}).click();assert.equal(await page.locator('.parameter-group[open]').count(),0);
await page.getByRole('button',{name:'全部展开',exact:true}).click();assert.equal(await page.locator('.parameter-group[open]').count(),8);
await page.getByLabel('查看H路').selectOption('1');await expect(page.locator('#frameDiagram')).toContainText('H1');
await page.getByRole('button',{name:'标签偏差示意',exact:true}).click();await expect(page.locator('#assignmentDiagram')).toContainText('编码器归属：A6');
await page.getByLabel('起始点云列').selectOption('8');await expect(page.locator('#hierarchyDiagram')).toContainText('S8');
await page.getByLabel('起始点云列').selectOption('7');
await page.getByRole('button',{name:'回波附近 · ns',exact:true}).click();
const echoStart=Number(await page.getByLabel('时序显示起点').inputValue()),echoEnd=Number(await page.getByLabel('时序显示终点').inputValue());assert(echoStart>30&&echoEnd<31);
await page.getByLabel('时序显示起点').fill('30.65');await page.getByLabel('时序显示终点').fill('30.69');await page.getByRole('button',{name:'应用精确窗口'}).click();await expect(page.locator('#windowError')).toHaveText('');
await page.getByLabel('时序显示终点').fill('30');await page.getByRole('button',{name:'应用精确窗口'}).click();await expect(page.locator('#windowError')).toContainText('终点大于起点');
await page.getByRole('button',{name:'两个列 slot',exact:true}).click();
await page.locator('#navigatorHit').scrollIntoViewIfNeeded();const nav=await page.locator('#navigatorHit').boundingBox();
await page.mouse.move(nav.x+nav.width*.32,nav.y+nav.height/2);await page.mouse.down();await page.mouse.move(nav.x+nav.width*.48,nav.y+nav.height/2,{steps:8});await page.mouse.up();
const dragStart=await page.getByLabel('时序显示起点').inputValue();assert(Number(dragStart)>100);
await page.getByRole('button',{name:'两个列 slot',exact:true}).click();
await page.getByRole('button',{name:'B 成组 / 突发发射',exact:false}).click();await expect(page.locator('#strategyNote')).toContainText('尚未执行突发仿真');
await page.getByRole('button',{name:'SPAD / TDC 状态延续',exact:true}).click();await expect(page.locator('#causeNote')).toContainText('不自动重置');
await page.getByLabel('观察线阵行').selectOption('15');await expect(page.locator('.state-inspector .pending')).toContainText('V15');
await page.getByLabel('帧率 / Hz',{exact:true}).fill('500');await expect(page.locator('#draftBanner')).toBeVisible();
await page.getByRole('button',{name:'导出设计草案',exact:true}).click();
await page.getByRole('button',{name:'恢复参考',exact:true}).click();await expect(page.locator('#draftBanner')).toBeHidden();
await page.getByRole('button',{name:'查看拟定运行流程 →',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'关闭',exact:true}).click();
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.dataset.ready==='true');
return {errors,echoWindow:[echoStart,echoEnd],dragStart,checks:'collapse, expand, H view, angle labels, column selection, ns preset, exact window, invalid window, drag, strategy, cause, row, draft, export, reset, dialog, ordinary refresh passed',screenshot:await (async()=>{await page.locator('.timing-panel').evaluate(el=>el.scrollIntoView({block:'start'}));return await page.screenshot({fullPage:false});})()};