/* Frontend-only review prototype. Render frozen Python arrays; no physics here. */
'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone = value => JSON.parse(JSON.stringify(value));
const get = (object, path) => path.split('.').reduce((v, key) => v?.[key], object);
const set = (object, path, value) => {const parts=path.split('.'), key=parts.pop();parts.reduce((v,k)=>v[k],object)[key]=value;};
const fmt = (n, digits=2) => (Math.abs(Number(n))<.5*10**(-digits)?0:Number(n)).toLocaleString('en-US',{maximumFractionDigits:digits});
const KEY='spad-b-ui-preview-v2';
let data, draft, base, selectedChannels=[0], selectedH, selectedV, windowRange, peakWindow, toastTimer;
const fieldNames=new Map();
const concepts={
 tx:['Tx 发射','描述整个光斑每一发的能量及 H/V 角分布。角度单元是对方向空间的离散划分；份额的参考面为 Tx 光学之后。有限角域外的能量保留为截断损失。'],
 scene:['场景与传播','当前样例使用同距离、同反射率的扩展朗伯目标，计入大气双程损耗和接收入瞳。场景负责传播，Tx/Rx 分别负责发射与接收光学。'],
 rx:['Rx 成像','H/V 分别使用水平和垂直等效焦距，并计入两轴成像倒置。正入射角对应负像面位置；所有空间图采用右正左负、上正下负。PSF 再按完整像素积分，得到 PDE/FF 前的入射光子。'],
 spad:['SPAD 物理像素','物理像素是光学映射和器件状态的基本单位。PDE/FF 将入射光子转为候选雪崩，器件死时间决定哪些雪崩能实际发生。'],
 readout:['读出通道','每个通道由一组物理 SPAD 构成。读出逻辑和 TDC 决定最终时间戳；通道编号、像素坐标与角度单元分别管理。']
};
function help(path){return data.help.experiments?.[path]||data.help[path.split('.').at(-1)]||{};}
function numeric(path,label,unit='',wide=false){fieldNames.set(path,label);const h=help(path);return `<label class="field ${wide?'wide':''}" title="${esc(h.description||label)}"><span class="field-title">${esc(label)}</span><span class="input-unit"><input type="number" step="any" data-path="${path}" value="${esc(get(draft,path))}" aria-label="${esc(label)}">${unit?`<span class="unit">${esc(unit)}</span>`:''}</span></label>`;}
function select(path,label,options){fieldNames.set(path,label);return `<label class="field wide" title="${esc(help(path).description||label)}"><span>${label}</span><select data-path="${path}" aria-label="${label}">${options.map(([v,l])=>`<option value="${v}" ${get(draft,path)===v?'selected':''}>${l}</option>`).join('')}</select></label>`;}
function matrix(title,unit,col1,col2,rows){return `<div class="compact-matrix"><div class="matrix-head"><span>${title}</span><span class="unit">${unit}</span></div><div class="matrix-row headers"><span></span><span>${col1}</span><span>${col2}</span></div>${rows.map(([axis,p1,p2])=>`<div class="matrix-row"><span>${axis}</span>${[p1,p2].map((path,i)=>{const label=title+' '+axis+' '+[col1,col2][i];fieldNames.set(path,label);return `<label><input type="number" step="any" data-path="${path}" value="${esc(get(draft,path))}" aria-label="${label}" title="${esc(help(path).description||label)}"></label>`;}).join('')}</div>`).join('')}</div>`;}
function toggle(path,label){fieldNames.set(path,label);return `<label class="toggle-row"><span>${label}</span><span class="switch"><input type="checkbox" data-path="${path}" ${get(draft,path)?'checked':''} aria-label="${label}"></span></label>`;}
function subhead(title){return `<div class="subhead">${title}</div>`;}
function group(id,code,title,summary,body,open=false){return `<details class="parameter-group" data-group="${id}" ${open?'open':''}><summary><span class="group-text"><strong>${title}</strong><small>${summary}</small></span><span class="group-code">${code}</span></summary><div class="group-body">${body}</div></details>`;}
function curveEditor(kind,label){const item=draft.spectral_inputs[kind];const opts=[['basic','基础'],['csv','CSV'],['manual','手动']];if(kind==='solar')opts.unshift(['standard','标准谱']);const path='spectral_inputs.'+kind+'.mode';fieldNames.set(path,label+'输入模式');let body='';if(item.mode==='basic'){body=`<div class="field-grid">${numeric(`spectral_inputs.${kind}.basic.amplitude`,'幅值')}${numeric(`spectral_inputs.${kind}.basic.center_nm`,'中心波长','nm')}${numeric(`spectral_inputs.${kind}.basic.width_nm`,'宽度','nm')}</div>`;}else if(item.mode==='standard'){body='<div class="curve-summary">使用项目标准太阳光谱，以照度进行归一化。<br>光谱与照度分别描述形状和强度。</div>';}else {const points=item[item.mode+'_points'];body=`<div class="curve-summary">${item.mode==='csv'?esc(item.csv_name||'采样曲线'):'手动采样点'}<br>${points.length} 个采样点 · ${esc(item.interpolation)} 插值${points.length?`<svg class="curve-mini" viewBox="0 0 260 68" aria-label="${label}样例采样点"></svg>`:''}<button type="button" class="text-button curve-data" data-curve="${kind}">查看 / 编辑采样点</button></div>`;}return `<div class="curve-editor" data-curve-group="${kind}"><div class="subhead">${label}</div><div class="curve-modes">${opts.map(([v,l])=>`<button type="button" data-curve-mode="${v}" data-curve-kind="${kind}" class="${item.mode===v?'active':''}">${l}</button>`).join('')}</div>${body}</div>`;}
function renderParameters(){
 const o=draft.optics,d=draft.device,r=draft.readout,t=draft.timing;
 let opened={};document.querySelectorAll('.parameter-group').forEach(el=>opened[el.dataset.group]=el.open);
 if(!Object.keys(opened).length){try{opened=JSON.parse(localStorage.getItem(KEY+'-open')||'{}');}catch{}}
 const m=(...args)=>matrix(...args),n=(...args)=>numeric(...args),s=(...args)=>select(...args);
 const tx=subhead('光源与发射效率')+`<div class="field-grid">${n('optics.wavelength_nm','激光波长','nm')}${n('optics.total_pulse_energy_nj','全光斑能量 · Tx前','nJ')}${s('optics.pulse_shape','时间脉冲形状',[['gaussian','高斯脉冲'],['rectangular','矩形脉冲']])}${n('optics.pulse_fwhm_ps','脉宽 FWHM','ps')}${n('optics.tx_efficiency','Tx 光学效率')}</div>`+subhead('发射角分布')+`<div class="field-grid">${s('optics.tx_model','Tx 分布模型',[['gaussian','高斯角分布'],['uniform','角域内均匀分布'],['dataset','导入光学数据库']])}</div><div data-visible="tx-gaussian">${m('光束角参数','mrad','角中心','FWHM',[['H','optics.tx_center_h_mrad','optics.tx_fwhm_h_mrad'],['V','optics.tx_center_v_mrad','optics.tx_fwhm_v_mrad']])}</div><details class="subdetails"><summary>角域与覆盖范围</summary>${m('构造 Tx 角域','mrad','最小值','最大值',[['H','optics.angle_h_min_mrad','optics.angle_h_max_mrad'],['V','optics.angle_v_min_mrad','optics.angle_v_max_mrad']])}<p class="field-note">有限角域外的光保留为截断损失。Rx 数据库需覆盖查询角度。</p></details><p class="field-note" data-visible="tx-dataset">选择数据库后，角度份额将由文件定义。原型仅预览模式切换。</p>`;
 const scene=subhead('目标')+`<div class="field-grid">${n('optics.range_m','目标距离','m')}${n('optics.target_reflectivity','目标反射率')}</div>`+subhead('传播')+`<div class="field-grid">${n('optics.atmospheric_one_way_transmission','单程大气透过率')}${n('optics.overlap_factor','Tx / Rx 重叠因子')}</div><p class="field-note">当前模型：同距离的扩展朗伯目标。</p>`;
 const rx=subhead('接收入瞳')+`<div class="field-grid">${s('optics.rx_aperture_shape','入瞳形状',[['rectangle','矩形'],['ellipse','椭圆'],['circle','圆形']])}<div class="field wide" data-visible="aperture-axes"><div class="field-grid">${n('optics.rx_aperture_width_mm','水平全尺寸','mm')}${n('optics.rx_aperture_height_mm','垂直全尺寸','mm')}</div></div><div class="field wide" data-visible="aperture-circle">${n('optics.rx_aperture_mm','入瞳直径','mm')}</div></div>`+subhead('位置映射与 PSF')+`<div class="field-grid">${s('optics.rx_model','像面映射模型',[['gaussian_psf','几何映射 + 高斯 PSF'],['uniform_pixel','均匀像素分配'],['dataset','导入光学数据库']])}<div class="field wide" data-visible="rx-synthetic"><div class="field-grid">${n('optics.rx_efficiency','Rx 收光效率')}</div></div><div class="field wide" data-visible="rx-gaussian"><div class="field-grid">${n('optics.focal_length_h_mm','水平等效焦距 f_H','mm')}${n('optics.focal_length_v_mm','垂直等效焦距 f_V','mm')}${n('optics.psf_sigma_um','PSF 标准差 σ','μm')}${n('optics.rx_offset_x_um','像面 x 偏移','μm')}${n('optics.rx_offset_y_um','像面 y 偏移','μm')}</div></div></div><details class="subdetails" data-visible="rx-synthetic"><summary>构造 Rx 数据库覆盖</summary>${m('Rx 角度覆盖域','mrad','最小值','最大值',[['H','optics.rx_angle_h_min_mrad','optics.rx_angle_h_max_mrad'],['V','optics.rx_angle_v_min_mrad','optics.rx_angle_v_max_mrad']])}</details><p class="field-note" data-visible="rx-dataset">导入数据将提供实际像素边界、效率与 PSF。后端导入将在正式版接入。</p>${curveEditor('filter','滤光片透过率')}`;
 const spad=subhead('像素与探测响应')+`<div class="field-grid">${n('optics.pixel_pitch_um','像素节距','μm')}${n('device.fill_factor','填充因子 FF')}${s('device.detector_operation','SPAD 工作方式',[['gated','仅门内工作'],['free_running','持续工作 / 门内记录']])}</div>${curveEditor('pde','PDE 光谱')}`+subhead('器件噪声与恢复')+`<div class="field-grid">${n('device.dcr_cps_per_spad','暗计数 / SPAD','cps')}${n('device.other_noise_cps_per_spad','其他随机噪声','cps')}${n('device.spad_dead_time_ns','SPAD 死时间','ns')}${n('device.spad_jitter_fwhm_ps','SPAD 抖动 FWHM','ps')}</div>`;
 const modes=Object.entries(data.readout_modes).filter(([k,v])=>k!=='analytic_reference'&&v?.label).map(([k,v])=>[k,v.label]);
 const readout=subhead('通道布局与空间分组')+m('二维布局','个','通道数量','每通道 binning',[['H','optics.channels_h','device.H_binning'],['V','optics.channels_v','device.V_binning']])+`<div class="derived">固定样例：<b>${data.optics.array_shape[1]} × ${data.optics.array_shape[0]}</b> 物理像素，<b>${base.optics.channels_h*base.optics.channels_v}</b> 个通道。每通道 SPAD 数由 H × V binning 派生。</div>`+subhead('电子读出')+`<div class="field-grid">${s('readout.readout_mode','读出架构',modes)}${n('readout.tdc_bin_ps','TDC 时间 bin','ps')}${n('readout.tdc_dead_time_ns','TDC 死时间','ns')}${n('readout.other_jitter_fwhm_ps','电子学抖动 FWHM','ps')}${n('optics.calibration_delay_ns','标定延迟','ns')}</div><details class="subdetails"><summary>TDC 容量与符合逻辑</summary><div class="field-grid">${n('readout.tdc_count','共享 TDC 个数')}${n('readout.tdc_max_hits_per_cycle','每 TDC 记录上限')}${n('readout.or_pulse_width_ns','OR 脉宽','ns')}${n('readout.coincidence_window_ns','符合时间窗','ns')}${n('readout.coincidence_threshold','符合阈值')}</div><p class="field-note">参数适用范围由读出架构决定；正式版将按模型显示有效项。</p></details>`;
 const background=toggle('optics.solar_enabled','太阳光')+`<div data-visible="solar"><div class="field-grid">${n('optics.solar_illuminance_lux','目标面太阳照度','lux')}${n('optics.solar_reflectivity','太阳背景灰反射率')}</div>${curveEditor('solar','太阳光谱')}</div><p class="field-note" data-visible="no-solar">已关闭。开启后配置照度与光谱。</p>`+subhead('其他环境光')+toggle('optics.other_light_enabled','其他环境光')+`<div data-visible="ambient"><div class="field-grid">${n('optics.other_light_scale','环境光强度倍率')}</div>${curveEditor('other','环境光谱')}</div><p class="field-note" data-visible="no-ambient">已关闭。开启后配置强度与光谱。</p>`;
 const acquisition=subhead('采集时序')+`<div class="field-grid">${n('timing.period_ns','发射周期','ns')}${n('timing.laser_shots','累计发数','发')}${n('timing.gate_start_ns','接收门起点','ns')}${n('timing.gate_width_ns','接收门宽度','ns')}</div>`+subhead('随机采样与统计')+`<div class="field-grid">${n('rng_seed','随机种子')}</div><div class="derived">样例重复采集：<b>${data.statistics.trial_count}</b> 次<br>样例纯噪声均值：<b>${data.statistics.noise_trial_count}</b> 次</div><p class="field-note">统计次数随样例固化。正式版将在这里接入重复采集设置。</p>`;
 $('parameterGroups').innerHTML=[group('tx','TX','Tx 发射',`${o.wavelength_nm} nm · ${o.total_pulse_energy_nj} nJ · ${o.tx_model==='gaussian'?'高斯角分布':o.tx_model}`,tx,opened.tx??true),group('scene','SCENE','场景与传播',`${o.range_m} m · 反射率 ${o.target_reflectivity}`,scene,opened.scene??false),group('rx','RX','Rx 接收光学',`位置映射 · PSF · 滤光片`,rx,opened.rx??false),group('spad','SPAD','SPAD 与阵列',`器件响应 · PDE · 噪声`,spad,opened.spad??false),group('readout','READOUT','读出与分组',`H ${o.channels_h} × V ${o.channels_v} 通道 · 空间 binning`,readout,opened.readout??false),group('background','LIGHT','环境光',`太阳光${o.solar_enabled?'开启':'关闭'} · 其他光${o.other_light_enabled?'开启':'关闭'}`,background,opened.background??false),group('acquisition','ACQ','采集与统计',`${t.laser_shots} 发 · seed ${draft.rng_seed}`,acquisition,opened.acquisition??false)].join('');
 document.querySelectorAll('.parameter-group').forEach(el=>el.addEventListener('toggle',saveOpenState));
 drawCurveMinis();updateVisibility();markChanges();
}
function drawCurveMinis(){document.querySelectorAll('.curve-mini').forEach(svg=>{const kind=svg.closest('[data-curve-group]').dataset.curveGroup,item=draft.spectral_inputs[kind],points=item[item.mode+'_points'];if(!points?.length)return;const xs=points.map(p=>p.wavelength_nm),ys=points.map(p=>p.value),xmin=Math.min(...xs),xmax=Math.max(...xs),ymax=Math.max(...ys);const coords=points.map(p=>[(p.wavelength_nm-xmin)/(xmax-xmin||1)*244+8,54-(ymax?p.value/ymax:0)*44]);svg.innerHTML=`<path d="M8 56H254" fill="none" stroke="#284451"/><polyline points="${coords.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#58cfc7" stroke-width="1.3"/>${coords.map(([x,y])=>`<circle cx="${x}" cy="${y}" r="1.7" fill="#8fcced"/>`).join('')}<text x="8" y="67" fill="#6f95a9" font-size="8">${xmin} nm</text><text x="217" y="67" fill="#6f95a9" font-size="8">${xmax}</text>`;});}
function updateVisibility(){const checks={'tx-gaussian':draft.optics.tx_model==='gaussian','tx-dataset':draft.optics.tx_model==='dataset','rx-gaussian':draft.optics.rx_model==='gaussian_psf','rx-synthetic':draft.optics.rx_model!=='dataset','rx-dataset':draft.optics.rx_model==='dataset','aperture-axes':draft.optics.rx_aperture_shape!=='circle','aperture-circle':draft.optics.rx_aperture_shape==='circle','solar':draft.optics.solar_enabled,'no-solar':!draft.optics.solar_enabled,'ambient':draft.optics.other_light_enabled,'no-ambient':!draft.optics.other_light_enabled};document.querySelectorAll('[data-visible]').forEach(el=>el.classList.toggle('hidden',!checks[el.dataset.visible]));}
function saveOpenState(){const open={};document.querySelectorAll('.parameter-group').forEach(el=>open[el.dataset.group]=el.open);localStorage.setItem(KEY+'-open',JSON.stringify(open));}
function changes(){return [...fieldNames].filter(([p])=>JSON.stringify(get(draft,p))!==JSON.stringify(get(base,p)));}
function markChanges(){const changed=JSON.stringify(draft)!==JSON.stringify(base);$('draftState').textContent=changed?'草稿已修改':'初版共有默认值';$('draftState').classList.toggle('amber',changed);$('staleBanner').classList.toggle('hidden',!changed);document.querySelectorAll('[data-path]').forEach(el=>el.classList.toggle('changed',JSON.stringify(get(draft,el.dataset.path))!==JSON.stringify(get(base,el.dataset.path))));}
function saveDraft(){localStorage.setItem(KEY,JSON.stringify(draft));markChanges();const o=draft.optics;const summaries={tx:`${o.wavelength_nm} nm · ${o.total_pulse_energy_nj} nJ · ${o.tx_model==='gaussian'?'高斯角分布':o.tx_model}`,scene:`${o.range_m} m · 反射率 ${o.target_reflectivity}`,readout:`H ${o.channels_h} × V ${o.channels_v} 通道 · 空间 binning`,background:`太阳光${o.solar_enabled?'开启':'关闭'} · 其他光${o.other_light_enabled?'开启':'关闭'}`,acquisition:`${draft.timing.laser_shots} 发 · seed ${draft.rng_seed}`};for(const [id,text]of Object.entries(summaries)){const el=document.querySelector(`[data-group="${id}"] .group-text small`);if(el)el.textContent=text;}}
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),4500);}
function dialog(title,html){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;$('previewDialog').showModal();}
function download(name,dataObject){const blob=new Blob([typeof dataObject==='string'?dataObject:JSON.stringify(dataObject,null,2)],{type:typeof dataObject==='string'?'text/csv;charset=utf-8':'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function color(f){const stops=[[0,[12,32,51]],[.24,[26,79,111]],[.54,[27,145,154]],[.8,[112,211,185]],[1,[249,239,175]]];f=Math.max(0,Math.min(1,f));let i=1;while(i<stops.length-1&&f>stops[i][0])i++;const [a,ca]=stops[i-1],[b,cb]=stops[i];return `rgb(${ca.map((v,k)=>Math.round(v+(cb[k]-v)*(f-a)/(b-a))).join(',')})`;}
function heatmap(id,rows,xedges,yedges,options={}){
 const root=$(id),ny=rows.length,nx=rows[0].length,flat=rows.flat(),max=options.fixedMax??Math.max(...flat),xmin=xedges[0],xmax=xedges.at(-1),ymin=yedges[0],ymax=yedges.at(-1),aspect=(xmax-xmin)/(ymax-ymin),w=Math.min(263,159*aspect),h=w/aspect,left=42+(263-w)/2,top=25+(159-h)/2;
 const sx=v=>left+(v-xmin)/(xmax-xmin)*w,sy=v=>top+(ymax-v)/(ymax-ymin)*h;
 const val=v=>options.percent?fmt(v*100,1)+'%':(v!==0&&Math.abs(v)<.01?v.toExponential(1):fmt(v,2));
 let html=`<svg viewBox="0 0 382 229" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="${id}-gradient" x1="0" x2="0" y1="1" y2="0">${[0,.24,.54,.8,1].map(t=>`<stop offset="${t*100}%" stop-color="${color(t)}"/>`).join('')}</linearGradient></defs><text x="${left}" y="14">${esc(options.yLabel||'V · mrad')} ↑</text><text x="321" y="14" style="font-size:8px">${esc(options.colorLabel||'份额')}</text>`;
 rows.forEach((row,y)=>row.forEach((v,x)=>{const label=`H[${x}], V[${y}] · ${xedges[x]}…${xedges[x+1]} / ${yedges[y]}…${yedges[y+1]} · ${v}`;html+=`<rect class="cell" data-x="${x}" data-y="${y}" x="${sx(xedges[x])}" y="${sy(yedges[y+1])}" width="${sx(xedges[x+1])-sx(xedges[x])}" height="${sy(yedges[y])-sy(yedges[y+1])}" fill="${color(max?v/max:0)}" stroke="#0c1c27" stroke-opacity=".36" stroke-width=".5" ${options.interactive?`role="button" tabindex="0" aria-label="选择角度 H ${x} V ${y}"`:''}><title>${esc(label)}</title></rect>`;}));
 if(options.groups){const gh=base.optics.channels_h,gv=base.optics.channels_v;for(let v=0;v<gv;v++)for(let u=0;u<gh;u++){const x=sx(xedges[u*base.device.H_binning]),y=sy(yedges[(v+1)*base.device.V_binning]),ww=sx(xedges[(u+1)*base.device.H_binning])-x,hh=sy(yedges[v*base.device.V_binning])-y;html+=`<rect class="channel-frame" x="${x}" y="${y}" width="${ww}" height="${hh}"/><text class="channel-label" x="${x+5}" y="${y+11}">H${u} V${v}</text>`;}}
 if(options.selected){const [x,y]=options.selected;html+=`<rect class="selected-cell" x="${sx(xedges[x])+.7}" y="${sy(yedges[y+1])+.7}" width="${sx(xedges[x+1])-sx(xedges[x])-1.4}" height="${sy(yedges[y])-sy(yedges[y+1])-1.4}"/>`;}
 for(let i=0;i<=4;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;html+=`<text x="${sx(x)}" y="201" text-anchor="middle">${fmt(x,1)}</text><text x="34" y="${sy(y)+3}" text-anchor="end">${fmt(y,1)}</text>`;}
 html+=`<text x="${left+w/2}" y="220" text-anchor="middle">${esc(options.xLabel||'H · mrad')} →</text><rect x="323" y="${top}" width="10" height="${h}" fill="url(#${id}-gradient)" rx="2"/>`;
 for(let i=0;i<=4;i++)html+=`<text x="339" y="${top+h*i/4+3}" style="font-size:8px">${val(max*(1-i/4))}</text>`;
 root.innerHTML=html+'</svg>';
 root.querySelectorAll('.cell').forEach(cell=>{cell.addEventListener('pointerenter',()=>{const x=+cell.dataset.x,y=+cell.dataset.y;const coordinate=options.pixel?`像素 x[${x}], y[${y}]`:`角单元 H[${x}], V[${y}]`;$('spatialHover').textContent=`${coordinate} · 中心 (${fmt((xedges[x]+xedges[x+1])/2,3)}, ${fmt((yedges[y]+yedges[y+1])/2,3)}) ${options.pixel?'μm':'mrad'} · ${val(rows[y][x])}${options.pixel&&!options.percent?' 光子 / 发':''}`;});if(options.interactive){const choose=()=>{selectedH=+cell.dataset.x;selectedV=+cell.dataset.y;renderMapping();};cell.addEventListener('click',choose);cell.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});}});
}
function renderSpatial(){const o=data.optics;heatmap('txPlot',o.tx_energy_fraction,o.tx_h_edges_mrad,o.tx_v_edges_mrad,{percent:true});heatmap('sensorPlot',data.illumination,data.x_edges_um,data.y_edges_um,{xLabel:'x · μm',yLabel:'y · μm',colorLabel:'光子/发',pixel:true,groups:$('showGroups').checked});}
function channelName(id){return `H${id%base.optics.channels_h} · V${Math.floor(id/base.optics.channels_h)}`;}
function renderPicker(){$('channelPicker').style.gridTemplateColumns=`repeat(${base.optics.channels_h},minmax(0,1fr))`;$('channelPicker').innerHTML=data.histogram.counts.map((_,id)=>`<button class="${selectedChannels.includes(id)?'selected':''}" aria-pressed="${selectedChannels.includes(id)}" data-channel="${id}" title="通道 ${id}：${channelName(id)}">${channelName(id)} <span>/${id}</span></button>`).reverse().reduce((rows,html,i)=>{const row=Math.floor(i/base.optics.channels_h);(rows[row]??=[]).unshift(html);return rows;},[]).flat().join('');$('channelInput').value=selectedChannels.join(', ');}
function parseChannels(text){const count=data.histogram.counts.length,result=new Set();if(!text.trim())throw Error('请输入至少一个通道编号。');for(const term of text.split(/[,，]/)){const match=term.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!match)throw Error('格式示例：0, 2, 4-5。');const start=+match[1],end=match[2]===undefined?start:+match[2];if(start>end||end>=count)throw Error(`通道编号范围为 0–${count-1}，起点不能大于终点。`);for(let i=start;i<=end;i++)result.add(i);}return [...result].sort((a,b)=>a-b);}
function canvasSetup(canvas){const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);return [ctx,rect.width,rect.height];}
function visibleSeries(){return Object.fromEntries([...document.querySelectorAll('[data-series]')].map(x=>[x.dataset.series,x.checked]));}
function histMaximum(ch,range,series){return PhotonHistogram.maximum(data,ch,range,series);}
function drawHistogram(canvas,ch,range,ymax,series,overview=false){return PhotonHistogram.draw(canvas,data,ch,range,ymax,series,overview,windowRange);}
function renderHistograms(){
 $('histogramPlots').classList.toggle('multi',selectedChannels.length>1);
 $('histogramPlots').innerHTML=selectedChannels.map(ch=>`<article class="hist-plot"><div class="hist-plot-head"><strong>CH ${String(ch).padStart(2,'0')} <span> / ${channelName(ch)}</span></strong><span>${fmt(data.histogram.counts[ch].reduce((a,b)=>a+b,0),0)} 条记录</span></div><canvas data-hist="${ch}" aria-label="通道 ${ch} 探测直方图"></canvas><div class="overview-chart-label"><span>全门概览 · 拖动窗口或边界</span><span class="window-key">橙色：当前观察窗口</span></div><canvas class="overview-canvas" data-overview="${ch}" aria-label="通道 ${ch} 全门概览"></canvas><div class="local-window"><label>起点<input type="number" step="any" data-window-start="${ch}" aria-label="通道 ${ch} 观察窗口起点"></label><span>—</span><label>终点<input type="number" step="any" data-window-end="${ch}" aria-label="通道 ${ch} 观察窗口终点"></label><span>ns</span><button class="quiet small" data-window-apply="${ch}">应用</button></div><p class="window-note">精确时间输入 · 所选通道同步缩放</p></article>`).join('');
 const gate=[data.histogram.edges_ns[0],data.histogram.edges_ns.at(-1)];
 selectedChannels.forEach(ch=>{const canvas=document.querySelector(`[data-overview="${ch}"]`);PhotonHistogram.bindOverview(canvas,gate,()=>windowRange,range=>{windowRange=range;updateWindowInputs();redrawHistograms();});document.querySelector(`[data-window-apply="${ch}"]`).onclick=()=>{const lo=document.querySelector(`[data-window-start="${ch}"]`).valueAsNumber,hi=document.querySelector(`[data-window-end="${ch}"]`).valueAsNumber;if(!Number.isFinite(lo)||!Number.isFinite(hi)||lo>=hi||lo<gate[0]||hi>gate[1]){toast(`时间须在 ${gate[0]}–${gate[1]} ns 内，起点小于终点。`);return;}windowRange=[lo,hi];updateWindowInputs();redrawHistograms();};});
 updateWindowInputs();redrawHistograms();
}
function redrawHistograms(){const series=visibleSeries(),shared=$('sharedScale').checked,common=Math.max(...selectedChannels.map(ch=>histMaximum(ch,windowRange,series))),gate=[data.histogram.edges_ns[0],data.histogram.edges_ns.at(-1)];selectedChannels.forEach(ch=>{drawHistogram(document.querySelector(`[data-hist="${ch}"]`),ch,windowRange,shared?common:histMaximum(ch,windowRange,series),series);drawHistogram(document.querySelector(`[data-overview="${ch}"]`),ch,gate,histMaximum(ch,gate,{observed:true}),series,true);});}
function updateWindowInputs(){const value=v=>Number(v.toPrecision(12)).toString();$('timeMin').value=value(windowRange[0]);$('timeMax').value=value(windowRange[1]);document.querySelectorAll('[data-window-start]').forEach(el=>el.value=value(windowRange[0]));document.querySelectorAll('[data-window-end]').forEach(el=>el.value=value(windowRange[1]));}
function renderMapping(){const o=data.optics,nx=o.tx_h_edges_mrad.length-1,idx=selectedV*nx+selectedH,x=o.angular_h_centers_mrad[idx],y=o.angular_v_centers_mrad[idx];$('angleH').value=String(selectedH);$('angleV').value=String(selectedV);$('angleLabel').innerHTML=`H[${selectedH}] · V[${selectedV}]<small>中心 (${fmt(x,3)}, ${fmt(y,3)}) mrad · 范围 H ${fmt(o.tx_h_edges_mrad[selectedH],2)}…${fmt(o.tx_h_edges_mrad[selectedH+1],2)} / V ${fmt(o.tx_v_edges_mrad[selectedV],2)}…${fmt(o.tx_v_edges_mrad[selectedV+1],2)}</small>`;heatmap('anglePlot',o.psf_capture_fraction,o.tx_h_edges_mrad,o.tx_v_edges_mrad,{percent:true,fixedMax:1,interactive:true,selected:[selectedH,selectedV]});heatmap('psfPlot',data.angle_psfs[idx],data.x_edges_um,data.y_edges_um,{pixel:true,percent:true,xLabel:'x · μm',yLabel:'y · μm',groups:true});const fractions=o.angle_to_channel_fraction[idx];$('captureValue').textContent=fmt(o.psf_capture_fraction[selectedV][selectedH]*100,2)+'%';$('channelFractions').innerHTML=fractions.map((v,ch)=>`<div class="share-row"><span>CH ${ch} · H${ch%base.optics.channels_h} V${Math.floor(ch/base.optics.channels_h)}</span><div class="share-track"><div class="share-fill" style="width:${v*100}%"></div></div><span class="share-value">${fmt(v*100,2)}%</span></div>`).join('');renderCrosstalk();}
function showConcept(key){const [title,text]=concepts[key];$('overviewDetail').innerHTML=`<strong>${title}</strong><br>${text}`;$('overviewDetail').classList.remove('hidden');$('toggleOverview').setAttribute('aria-expanded','true');$('toggleOverview').innerHTML='收起概念说明 <span>−</span>';document.querySelectorAll('[data-concept]').forEach(el=>el.classList.toggle('selected',el.dataset.concept===key));}
function showChanges(){const rows=changes();dialog('当前参数草稿',`<p>以下为本地界面草稿的改动。图表仍显示固定样例，尚未重新计算。</p>${rows.length?`<table><thead><tr><td>参数</td><td>样例</td><td>当前草稿</td></tr></thead><tbody>${rows.map(([p,n])=>`<tr><td>${n}</td><td>${esc(get(base,p))}</td><td>${esc(get(draft,p))}</td></tr>`).join('')}</tbody></table>`:'<p>当前参数与固定样例一致。</p>'}`);}
function bind(){
 $('parameterGroups').addEventListener('change',e=>{const el=e.target;if(!el.matches('[data-path]'))return;let value=el.type==='checkbox'?el.checked:el.type==='number'?el.valueAsNumber:el.value;if(typeof value==='number'&&!Number.isFinite(value)){el.setCustomValidity('请输入有限数值');el.reportValidity();return;}el.setCustomValidity('');set(draft,el.dataset.path,value);updateVisibility();saveDraft();});
 $('parameterGroups').addEventListener('click',e=>{const mode=e.target.closest('[data-curve-mode]');if(mode){draft.spectral_inputs[mode.dataset.curveKind].mode=mode.dataset.curveMode;saveDraft();renderParameters();}const view=e.target.closest('[data-curve]');if(view){const kind=view.dataset.curve,item=draft.spectral_inputs[kind],key=item.mode+'_points';dialog('光谱采样点 · 界面草稿',`<p>波长单位 nm。此处只编辑草稿，样例图形保持不变。</p><textarea id="curvePoints" rows="10" aria-label="光谱采样点JSON">${esc(JSON.stringify(item[key],null,2))}</textarea><button id="saveCurvePoints" class="quiet small" style="margin-top:10px">保存到草稿</button><p id="curvePointError" class="inline-error"></p>`);$('saveCurvePoints').onclick=()=>{try{const parsed=JSON.parse($('curvePoints').value);if(!Array.isArray(parsed)||parsed.some(p=>!Number.isFinite(p.wavelength_nm)||!Number.isFinite(p.value)))throw Error('需要包含有限 wavelength_nm 与 value 数值的数组。');item[key]=parsed;saveDraft();renderParameters();$('previewDialog').close();toast('已保存采样点草稿。图表仍为固定样例。');}catch(err){$('curvePointError').textContent=err.message;}};}});
 $('collapseAll').onclick=()=>document.querySelectorAll('.parameter-group,.parameter-group details').forEach(el=>el.open=false);
 $('expandAll').onclick=()=>document.querySelectorAll('.parameter-group,.parameter-group details').forEach(el=>el.open=true);
 $('resetDraft').onclick=()=>{draft=clone(base);saveDraft();renderParameters();toast('已恢复沿用初版共有默认值的参数。');};
 $('runPreview').onclick=()=>dialog('前端预览阶段',`<p>这版用于确认页面布局和交互，尚未接入新的仿真流程。</p><p>你的参数修改已保存在本页草稿中。下方图表来自固定的 Python 样例，不会随草稿变化。</p><p>目前可以体验：参数分组、全折叠 / 展开、模式切换、通道选择、时间缩放、图层开关、二维角度与 PSF 联动。</p>`);
 $('reviewChanges').onclick=showChanges;
 $('exportDraft').onclick=()=>{download('b-interface-draft.json',{kind:'frontend_design_draft_not_simulation_config',snapshot_sha256:data.provenance.configuration_sha256,experiment:draft});toast('已导出界面草稿，带有原型标识。');};
 $('showSources').onclick=()=>dialog('样例来源',`<p>所有光学与探测数据由现有 Python 核心生成，光学参数为项目中的构造样例。</p><p>首次观测 seed：${data.provenance.rng_seed}<br>重复采集：${data.statistics.trial_count} 次，包含首次观测<br>纯噪声均值：${data.statistics.noise_trial_count} 次<br>配置指纹：${data.provenance.configuration_sha256}</p><p>原型中保存了结果快照；参数默认值仍通过项目 YAML 与 SimulationConfig 读取。</p>`);
 $('toggleOverview').onclick=()=>{if($('overviewDetail').classList.contains('hidden'))showConcept('rx');else{$('overviewDetail').classList.add('hidden');$('toggleOverview').setAttribute('aria-expanded','false');$('toggleOverview').innerHTML='概念与计算逻辑 <span>＋</span>';document.querySelectorAll('[data-concept]').forEach(el=>el.classList.remove('selected'));}};
 document.querySelectorAll('[data-concept]').forEach(el=>el.onclick=()=>showConcept(el.dataset.concept));
 $('toggleJobs').onclick=()=>{const hidden=$('jobHistory').classList.toggle('hidden');$('toggleJobs').setAttribute('aria-expanded',String(!hidden));};
 $('showGroups').onchange=renderSpatial;
 $('applyChannels').onclick=()=>{try{selectedChannels=parseChannels($('channelInput').value);$('histError').classList.add('hidden');renderPicker();renderHistograms();}catch(e){$('histError').textContent=e.message;$('histError').classList.remove('hidden');}};
 $('channelInput').onkeydown=e=>{if(e.key==='Enter')$('applyChannels').click();};
 $('channelPicker').onclick=e=>{const el=e.target.closest('[data-channel]');if(!el)return;const id=+el.dataset.channel;if(selectedChannels.includes(id)){if(selectedChannels.length===1){toast('至少保留一个展示通道。');return;}selectedChannels=selectedChannels.filter(ch=>ch!==id);}else selectedChannels.push(id);selectedChannels.sort((a,b)=>a-b);$('histError').classList.add('hidden');renderPicker();renderHistograms();};
 $('applyWindow').onclick=()=>{const lo=$('timeMin').valueAsNumber,hi=$('timeMax').valueAsNumber,min=data.histogram.edges_ns[0],max=data.histogram.edges_ns.at(-1);if(!Number.isFinite(lo)||!Number.isFinite(hi)||lo>=hi||lo<min||hi>max){$('histError').textContent=`时间窗口须位于 ${min}–${max} ns，且起点小于终点。`;$('histError').classList.remove('hidden');return;}windowRange=[lo,hi];$('histError').classList.add('hidden');renderHistograms();};
 $('focusPeak').onclick=()=>{windowRange=[...peakWindow];updateWindowInputs();$('histError').classList.add('hidden');renderHistograms();};
 $('showFullGate').onclick=()=>{windowRange=[data.histogram.edges_ns[0],data.histogram.edges_ns.at(-1)];updateWindowInputs();$('histError').classList.add('hidden');renderHistograms();};
 $('sharedScale').onchange=renderHistograms;document.querySelectorAll('[data-series]').forEach(el=>el.onchange=renderHistograms);
 $('angleH').onchange=()=>{selectedH=+$('angleH').value;renderMapping();};$('angleV').onchange=()=>{selectedV=+$('angleV').value;renderMapping();};
 $('exportHistogram').onclick=()=>{let csv='channel,time_ns,observed_counts,ideal_counts,noise_mean,sample_min,sample_max\n';for(const ch of selectedChannels)data.histogram.time_ns.forEach((t,i)=>{csv+=[ch,t,data.histogram.counts[ch][i],data.references[ch].counts[i],data.statistics.noise_mean[ch][i],data.statistics.lower?.[ch][i]??'',data.statistics.upper?.[ch][i]??''].join(',')+'\n';});download('b-fixed-sample-histograms.csv',csv);};
 $('exportMapping').onclick=()=>{const idx=selectedV*(data.optics.tx_h_edges_mrad.length-1)+selectedH;download('b-fixed-sample-psf-response.json',{reference_plane:'full_pixel_before_PDE_FF',h_index:selectedH,v_index:selectedV,h_mrad:data.optics.angular_h_centers_mrad[idx],v_mrad:data.optics.angular_v_centers_mrad[idx],pixel_fractions:data.angle_psfs[idx],channel_fractions:data.optics.angle_to_channel_fraction[idx],configuration_sha256:data.provenance.configuration_sha256});};
 $('closeDialog').onclick=$('dialogDone').onclick=()=>$('previewDialog').close();$('previewDialog').addEventListener('click',e=>{if(e.target===$('previewDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
 let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{renderHistograms();renderParameterFigure();},100);});
}
async function init(){
 const response=await fetch(document.body.dataset.snapshot,{cache:'no-store'});if(!response.ok)throw Error('样例数据加载失败：HTTP '+response.status);data=await response.json();base=data.preview.interface_configuration;draft=clone(base);
 try{const stored=JSON.parse(localStorage.getItem(KEY)||'null');if(stored&&stored.optics&&stored.device&&stored.spectral_inputs&&Number.isFinite(stored.optics.focal_length_h_mm)&&Number.isFinite(stored.optics.focal_length_v_mm))draft=stored;}catch{}
 renderParameters();bind();bindExtraPanels();
 const formula=String.raw`\mathbf{n}=\mathbf{P}\,\mathbf{D}\,\mathbf{q}`;
 try{katex.render(formula,$('responseFormula'),{displayMode:false,throwOnError:true});}catch(error){$('responseFormula').textContent='公式渲染失败：'+error.message+' / '+formula;}
 const b=data.optics.budget,a=data.audit;
 $('metrics').innerHTML=[['探测面信号光子',fmt(b.signal_sensor_incident_photons_per_pulse,2),'光子 / 发 · PDE / FF 前',true],['最终探测记录',fmt(a.final_records,0),`${base.timing.laser_shots} 发累计`,false],['SPAD 死时间损失',fmt(a.spad_dead_losses,0),'候选雪崩受器件恢复限制',false],['TDC / 容量损失',fmt(a.tdc_dead_losses+a.capacity_losses,0),'最终记录前的读出限制',false]].map(([label,val,note,accent])=>`<article class="metric"><p class="metric-label">${label}</p><p class="metric-number ${accent?'accent':''}">${val}</p><p class="metric-note">${note}</p></article>`).join('');
 $('sceneSummary').textContent=`${base.optics.range_m} m 目标 · ${base.optics.channels_h} × ${base.optics.channels_v} 通道 · ${base.timing.laser_shots} 发`;
 $('jobSummary').textContent=`seed ${data.provenance.rng_seed} · 配置 ${data.provenance.configuration_sha256.slice(0,8)}`;$('jobDate').textContent=data.provenance.utc.slice(0,19).replace('T',' ')+' UTC';
 $('txCoverage').textContent=`角域内能量 ${fmt(b.tx_angular_coverage_fraction*100,1)}%`;
 $('arraySummary').textContent=`${data.optics.array_shape[1]} × ${data.optics.array_shape[0]} 像素 · ${base.optics.channels_h} × ${base.optics.channels_v} 通道`;
 const times=data.references[0].high_resolution.time_ns;peakWindow=[Math.max(data.histogram.edges_ns[0],Math.floor(times[0])),Math.min(data.histogram.edges_ns.at(-1),Math.ceil(times.at(-1)))];windowRange=[...peakWindow];updateWindowInputs();
 $('statisticsNote').textContent=`固定样例：${data.statistics.trial_count} 次采集的逐 bin 最小—最大范围（含首次观测）`;$('binNote').textContent=`TDC bin ${base.readout.tdc_bin_ps} ps · 每次 ${base.timing.laser_shots} 发`;
 const nx=data.optics.tx_h_edges_mrad.length-1,ny=data.optics.tx_v_edges_mrad.length-1;selectedH=Math.floor(nx/2);selectedV=Math.floor(ny/2);
 $('angleH').innerHTML=Array.from({length:nx},(_,i)=>`<option value="${i}">${i}</option>`).join('');$('angleV').innerHTML=Array.from({length:ny},(_,i)=>`<option value="${i}">${i}</option>`).join('');
 $('auditContent').innerHTML=`<table><tbody>${[['入瞳信号光子 / 发',fmt(b.signal_rx_incident_photons_per_pulse,5)],['探测面信号光子 / 发',fmt(b.signal_sensor_incident_photons_per_pulse,5)],['理想候选雪崩 / 发',fmt(b.signal_candidate_avalanches_per_pulse,5)],['能量守恒残差 / J',b.energy_balance_residual_j],['模型版本',data.provenance.model_version],['配置指纹',data.provenance.configuration_sha256.slice(0,24)+'…']].map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</tbody></table><p class="field-note">构造光学；静态同距离朗伯场景；当前测距未经 B 专用检测门限标定。</p><details class="explanation"><summary>完整工况与算法快照</summary><pre>${esc(JSON.stringify(data.configuration,null,2))}</pre></details>`;
 renderSpatial();renderPicker();renderHistograms();renderMapping();document.body.dataset.ready='true';
}
init().catch(error=>{$('loadingError').textContent='前端预览加载失败\n'+error.message;$('loadingError').classList.remove('hidden');console.error(error);});
