const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8016/system?job=251f27c9e71e4842a3fd2d2bd6f21e38',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.dataset.ready==='true');
const noPickerOverflow=await page.locator('#channelPicker').evaluate(el=>el.scrollWidth<=el.clientWidth);assert(noPickerOverflow);
await page.locator('#channelInput').fill('30,31');await page.locator('#applyChannels').click();
if(!await page.locator('#jobHistory').isVisible())await page.locator('#toggleJobs').click();
await page.locator('[data-view-job="8791dc5875ec4086a52b8aa66871e17f"]').click();
await expect(page.locator('#channelLocator')).toHaveAttribute('data-configuration',/./);
await page.waitForFunction(()=>document.querySelectorAll('[data-map-channel]').length===6);
assert.equal(await page.locator('#channelInput').inputValue(),'0');assert.equal(await page.locator('[data-hist]').count(),1);
await page.locator('[data-map-channel="5"]').click();await expect(page.locator('#channelPicker [data-channel="5"]')).toHaveAttribute('aria-pressed','true');
await expect(page.locator('[data-series="error"]')).toBeDisabled();
await page.locator('[data-view-job="eff344ee56f24799876b5df6a08fa3e2"]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-map-channel]').length===8);
await page.locator('#channelInput').fill('3,4');await page.locator('#applyChannels').click();
await expect(page.locator('[data-series="error"]')).toBeEnabled();
const download=await tabbit.triggerAndWait('download',()=>page.locator('#exportHistogram').click());const downloaded={name:download.suggestedFilename(),failure:await download.failure()};assert.equal(downloaded.failure,null);
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>document.body.dataset.ready==='true');
await page.locator('#channelInput').fill('3,4');await page.locator('#applyChannels').click();
await page.setViewportSize({width:390,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.locator('#channelLocator').scrollIntoViewIfNeeded();
const responsive=await page.locator('#channelLocator').evaluate(el=>({width:el.getBoundingClientRect().width,columns:getComputedStyle(el.querySelector('.cl-layout')).gridTemplateColumns}));
await page.setViewportSize({width:1536,height:1180});
await page.locator('[data-map-channel="4"]').hover();
await page.evaluate(()=>scrollTo(0,document.querySelector('#histogramPanel').getBoundingClientRect().top+scrollY-15));
await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
assert.equal(errors.length,0,errors.join('\n'));
return {errors,noPickerOverflow,responsive,downloaded,screenshot:await page.screenshot({fullPage:false})};