await page.setViewportSize({width:1536,height:1180});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8016/system?job=eff344ee56f24799876b5df6a08fa3e2',{waitUntil:'networkidle'});
await page.waitForFunction(()=>document.body.dataset.ready==='true');
await page.locator('#histogramPanel').scrollIntoViewIfNeeded();
await expect(page.locator('#channelLocator')).toBeVisible();
assert.equal(await page.locator('#channelLocator [data-map-channel]').count(),8);
assert.equal(await page.locator('#channelLocator [data-channel]').count(),8);
assert.equal(await page.locator('#channelInput').count(),1);
await page.locator('#channelInput').fill('3,4');await page.locator('#applyChannels').click();
assert.equal(await page.locator('[data-map-channel].selected').count(),2);
assert.equal(await page.locator('[data-hist]').count(),2);
await page.locator('[data-map-channel="7"]').click();
await expect(page.locator('#channelPicker [data-channel="7"]')).toHaveAttribute('aria-pressed','true');
assert.equal(await page.locator('[data-hist="7"]').count(),1);
await page.locator('#channelPicker [data-channel="7"]').click();
await expect(page.locator('[data-map-channel="7"]')).toHaveAttribute('aria-pressed','false');
await page.locator('[data-map-channel="0"]').focus();await page.keyboard.press('Enter');
await expect(page.locator('#channelPicker [data-channel="0"]')).toHaveAttribute('aria-pressed','true');
await page.locator('#channelInput').fill('8');await page.locator('#applyChannels').click();
await expect(page.locator('#histError')).toBeVisible();assert.equal(await page.locator('[data-hist]').count(),3);
await page.locator('#channelInput').fill('3,4');await page.locator('#applyChannels').click();
await page.locator('[data-cl="spot-visible"]').uncheck();assert.equal(await page.locator('[data-cl="spot"]').getAttribute('opacity'),'0');await page.locator('[data-cl="spot-visible"]').check();
await page.locator('[data-cl="opacity"]').focus();await page.keyboard.press('Home');assert.equal(await page.locator('[data-cl="spot"]').getAttribute('opacity'),'0');await page.keyboard.press('End');assert.equal(await page.locator('[data-cl="spot"]').getAttribute('opacity'),'1');
await page.locator('[data-cl="opacity"]').fill('55');
await page.locator('[data-cl="pixel-grid"]').uncheck();assert.equal(await page.locator('[data-cl="pixels"]').evaluate(e=>getComputedStyle(e).display),'none');await page.locator('[data-cl="pixel-grid"]').check();
await expect(page.locator('[data-cl="formula"] .katex')).toBeVisible();
await page.locator('#timeMin').fill('660');await page.locator('#timeMax').fill('675');await page.locator('#applyWindow').click();assert.equal(await page.locator('[data-window-start="3"]').inputValue(),'660');assert.equal(await page.locator('[data-window-end="4"]').inputValue(),'675');
const oldBin=+(await page.locator('#replayBin').inputValue());await page.locator('#replayBin').fill(String(oldBin*2));await page.locator('#replayRecords').click();await expect(page.locator('#replayState')).toContainText('已重放');assert.equal(await page.locator('[data-map-channel].selected').count(),2);
await page.locator('[data-map-channel="4"]').hover();
const detail=await page.locator('[data-cl="detail-values"]').innerText();assert(detail.includes('4,845'));
await page.evaluate(()=>scrollTo(0,document.querySelector('#histogramPanel').getBoundingClientRect().top+scrollY-15));
await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
assert.equal(errors.length,0,errors.join('\n'));
return {errors,detail,source:await page.locator('[data-cl="source"]').innerText(),screenshot:await page.screenshot({fullPage:false})};