"""Build the shared light palette from presentation colors. No physics involved.

CSS uses var(--theme-color-<hex>, <original>) so dark remains unchanged.
Canvas renderers resolve the same palette; SVG attributes use the generated rules.
"""
import colorsys
from pathlib import Path
import re
import argparse

ROOT=Path(__file__).resolve().parents[1]
WEB=ROOT/'web'
CSS=[*WEB.glob('*.css'),* (WEB/'shared').glob('*.css')]
JS=[*WEB.glob('*.js'),* (WEB/'shared').glob('*.js')]
HEX=re.compile(r'#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b')
RGBA=re.compile(r'rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)(?:\s*,\s*([\d.]+))?\s*\)')


def rgba_key(match):
    return ''.join(f'{int(match[i]):02x}' for i in (1,2,3))+f'{round(float(match[4] or 1)*255):02x}'


def canonical(value):
    h=value[1:].lower()
    return ''.join(c*2 for c in h) if len(h)==3 else h[:6]


def light_color(h):
    rgb=[int(h[i:i+2],16)/255 for i in (0,2,4)]
    hue,l,s=colorsys.rgb_to_hls(*rgb)
    # Deep surfaces become near-white; bright labels/accents become dark ink.
    lightness=0.995-l*0.32 if l<0.46 else 0.38-(l-0.46)*0.4
    saturation=min(s,0.2) if l<0.46 else min(s,0.85)
    converted=colorsys.hls_to_rgb(hue,lightness,saturation)
    return '#'+''.join(f'{round(v*255):02x}' for v in converted)


def ink_color(h):
    hue,l,s=colorsys.rgb_to_hls(*[int(h[i:i+2],16)/255 for i in (0,2,4)])
    if l>=0.46:return light_color(h)
    return '#'+''.join(f'{round(v*255):02x}' for v in colorsys.hls_to_rgb(hue,0.35,min(s,0.6)))


def build():
    tokens={'#ffffff','#000000'}
    rgba=set()
    for path in CSS+JS:
        if path.name in ('theme.css','theme.js'):continue
        source=path.read_text(encoding='utf8')
        tokens.update(HEX.findall(source))
        rgba.update(rgba_key(m) for m in RGBA.finditer(source))
    palette={canonical(token):light_color(canonical(token)) for token in tokens}
    lines=['/* Generated by scripts/build-theme.py; dark fallbacks remain in page CSS. */',
        'html[data-theme="light"] { color-scheme:light;',
        *[f'  --theme-color-{h}: {palette[h]};' for h in sorted(palette)],'}',
        'html[data-theme="light"] {',*[f'  --theme-rgba-{h}: {light_color(h[:6])}{h[6:]};' for h in sorted(rgba)],'}',
        'html[data-theme="light"] {',*[f'  --theme-ink-{h}: {ink_color(h)};' for h in sorted(palette)],'}',
        'html[data-theme="dark"] { color-scheme:dark; }',
        '.theme-toggle{flex:none;align-self:center;white-space:nowrap;font:inherit;font-size:12px;line-height:1.4;padding:7px 11px;border:1px solid var(--line,#354b5e);border-radius:6px;background:var(--panel,var(--surface,#142230));color:var(--text,#e2ebf2);cursor:pointer;min-height:34px}',
        '.theme-toggle:focus-visible{outline:2px solid var(--cyan,#59d9cc);outline-offset:3px}',
        'html[data-theme="light"] .theme-toggle{background:#fff;color:#1c3548;border-color:#a8bdcd}',
        'html[data-theme="light"] .katex{color:inherit}',
        'html[data-theme="light"] button.primary{color:#fff}',
        '@media(max-width:760px){body>header nav{flex-wrap:wrap;gap:12px}body>header.app-header{height:auto;min-height:65px;flex-wrap:wrap;padding-top:12px;padding-bottom:12px}.theme-toggle{margin-left:auto}}']
    for token in sorted(tokens):
        mapped=palette[canonical(token)]+(token[7:] if len(token)==9 else '')
        for attr in ('fill','stroke'):
            lines.append(f'html[data-theme="light"] svg [{attr}="{token}"] {{{attr}:{mapped};}}')
        lines.append(f'html[data-theme="light"] svg text[fill="{token}"] {{fill:{ink_color(canonical(token))};}}')
    return '\n'.join(lines)+'\n'


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=WEB/'shared/theme.css';text=build()
    if args.check:
        if path.read_text(encoding='utf8')!=text:raise SystemExit('Theme palette is stale; run scripts/build-theme.py')
        print('Theme palette matches presentation sources.')
    else:path.write_text(text,encoding='utf8')
