import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const $=id=>document.getElementById(id);
const fmt=v=>BudgetNumbers.format(v);
const panel=$('schematicPanel'),host=$('sceneViewport');
let renderer,scene,camera,controls,root,packet,model,selected='tx',stale=false,playing=false,visible=true,frame=0,phase=0,lastTime=0,lastStage=-1;
let perspectiveCamera,orthographicCamera;
let pickables=[],labels=[],materials=[],palette={},view='perspective',channel=0,channelGroup=null,scope='overview';
const positions={perspective:[8,5,-12],front:[0,0,-16],top:[0,22,1],side:[-22,0,2],detector:[12,0,0]};
const lookAt={perspective:[0,0,1.5],front:[0,0,6],top:[0,0,3],side:[0,0,3],detector:[4.2,0,0]};
function fail(error){$('sceneError').hidden=false;$('sceneError').textContent='三维显示不可用：'+(error.message||error)+'。预算表和参数仍可正常使用。';$('sceneState').textContent='三维显示不可用';}
function themeColor(name,fallback){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback;}
function setPalette(){palette={source:themeColor('--tx-color','#e58386'),tx:themeColor('--tx-color','#e58386'),rx:themeColor('--rx-color','#7baff0'),detector:themeColor('--blue','#78aafa'),target:themeColor('--fov-color','#68b5a2'),scan:themeColor('--text','#e2ebf2')};if(renderer)renderer.setClearColor(themeColor('--bg','#0b1118'));}
function material(id,opacity=1){const m=new THREE.MeshBasicMaterial({color:palette[id],transparent:opacity<1,opacity,side:THREE.DoubleSide,depthWrite:opacity===1});m.userData={id,baseOpacity:opacity};materials.push(m);return m;}
function mesh(geometry,mat,id,position){const o=new THREE.Mesh(geometry,mat);o.userData.component=id;if(position)o.position.fromArray(position);root.add(o);pickables.push(o);return o;}
function line(points,id,opacity=1){const m=new THREE.LineBasicMaterial({color:palette[id],transparent:true,opacity});m.userData={id,baseOpacity:opacity};materials.push(m);const o=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p))),m);o.userData.component=id;root.add(o);pickables.push(o);return o;}
function label(id,text,position){const el=document.createElement('button');el.type='button';el.textContent=text;el.setAttribute('aria-label','选择'+text);el.onclick=()=>choose(id,true);$('sceneLabels').append(el);labels.push({id,el,position:new THREE.Vector3(...position)});}
function quad(points,id,opacity){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points.flat(),3));g.setIndex([0,1,2,0,2,3]);return mesh(g,material(id,opacity),id);}
function cone(points,id){for(let i=0;i<4;i++){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([...model.origin,...points[i],...points[(i+1)%4]],3));mesh(g,material(id,.035),id);line([model.origin,points[i]],id,.5);}line([...points,points[0]],id,.95);}
function ramp(value,id){const base=new THREE.Color(palette[id]);const bg=new THREE.Color(themeColor('--bg','#0b1118'));return bg.lerp(base,.12+.88*value);}
function heatmap(){for(const cell of model.tx_cells){const obj=quad(cell.vertices,'tx',.92);obj.material.color.copy(ramp(cell.relative_density,'tx'));obj.material.userData.relative=cell.relative_density;obj.userData.fraction=cell.fraction;obj.userData.power=cell.power_w;obj.renderOrder=2;}}
function detector(){const pos=model.detector_position;const [w,h]=model.detector_size;const plate=mesh(new THREE.BoxGeometry(.13,h+.15,w+.15),material('detector',.3),'detector',pos);plate.position.x-=.12;
 if(model.detector_cells.length){const mat=material('detector',1);mat.userData.instances=true;mat.color.set(0xffffff);const inst=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,.045),mat,model.detector_cells.length);const transform=new THREE.Object3D();transform.rotation.y=Math.PI/2;model.detector_cells.forEach((c,i)=>{transform.position.fromArray(c.center);transform.scale.set(c.size[0]*.91,c.size[1]*.91,1);transform.updateMatrix();inst.setMatrixAt(i,transform.matrix);inst.setColorAt(i,ramp(c.relative_energy,'detector'));});inst.instanceMatrix.needsUpdate=true;inst.instanceColor.needsUpdate=true;inst.userData.component='detector';root.add(inst);pickables.push(inst);}
 label('detector','SPAD · 独立放大',[pos[0],pos[1]+h/2+.45,pos[2]]);
}
function disposeRoot(){if(!root)return;const gs=new Set(),ms=new Set();root.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>ms.add(m));});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());scene.remove(root);$('sceneLabels').replaceChildren();labels=[];pickables=[];materials=[];}
function rebuild(){disposeRoot();root=new THREE.Group();scene.add(root);setPalette();
 if(scope==='local'){line(model.scan_fan.boundary,'scan',.5);label('scan','HFOV扇区参考 · 独立缩放',[0,-3.4,2]);}
 const grid=new THREE.GridHelper(16,16,new THREE.Color(palette.target),new THREE.Color(palette.target));grid.position.set(0,-3.3,3);grid.material.transparent=true;grid.material.opacity=.13;root.add(grid);
 if(scope==='local')mesh(new THREE.PlaneGeometry(9,9),material('target',.025),'target',[0,0,8.03]);
 if(scope==='overview')buildWholeField();else{cone(model.rx_corners,'rx');cone(model.tx_corners,'tx');heatmap();}
 // Exploded device glyphs, deliberately distinct from calibrated ray geometry.
 mesh(new THREE.BoxGeometry(.45,1.6,.4),material('source'),'source',model.source_position);
 label('source','VCSEL线阵',[0,1.4,-4]);
 const mirror=mesh(new THREE.BoxGeometry(1,.8,.09),material('scan',.7),'scan',model.origin);mirror.rotation.y=.55;
 label('scan','转镜 / 角度原点',[0,-.95,0]);
 const pupilGeometry=model.pupil_shape==='rectangle'?new THREE.PlaneGeometry(...model.pupil_size):new THREE.CircleGeometry(.5,48);
 const pupil=mesh(pupilGeometry,material('rx',.5),'rx',model.pupil_position);
 pupil.rotation.y=Math.PI/2;
 if(model.pupil_shape!=='rectangle')pupil.scale.set(...model.pupil_size,1);
 label('rx','Rx入瞳 · 展开示意',[2.2,1.05,0]);
 detector();
 line([model.source_position,model.origin],'source',.5);line([model.origin,model.pupil_position,model.detector_position],'rx',.5);
 label('tx',scope==='overview'?'整帧视场 · HFOV × VFOV':'Tx整列 / 单通道角域',scope==='overview'?[0,3.6,8]:[model.tx_corners[2][0],model.tx_corners[2][1]+.5,8]);
 label('target','目标参考面',scope==='overview'?[0,-3.6,8]:[model.rx_corners[0][0],model.rx_corners[0][1]-.7,8]);
 const axes=new THREE.AxesHelper(1.2);axes.position.set(-4,-3.3,0);root.add(axes);
 packet=mesh(new THREE.SphereGeometry(.1,12,8),new THREE.MeshBasicMaterial({color:palette.tx}),'source');packet.visible=false;pickables.pop();
 applyVisibility();paintSelection();updateChannel();render();
}
function buildWholeField(){for(const vertices of model.views.surface){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex([0,1,2,0,2,3]);mesh(g,material('target',.06),'target');}for(const points of model.views.lines)line(points,'target',.25);}
function selectionLine(points,color,opacity=1){const g=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p)));channelGroup.add(new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity})));}
function selectionFace(points,color,opacity=.25){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points.flat(),3));g.setIndex([0,1,2,0,2,3]);channelGroup.add(new THREE.Mesh(g,new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false})));}
function updateChannel(){if(!root||!model?.channel_regions)return;if(channelGroup){root.remove(channelGroup);channelGroup.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}channelGroup=new THREE.Group();root.add(channelGroup);const c=model.channel_regions[channel],slot=Number($('sceneSlot').value),column=model.views.column_regions[slot];
 if(scope==='local'){for(const [id,points]of [['tx',c.tx_corners],['rx',c.rx_corners]]){if(!$(id==='tx'?'sceneShowTx':'sceneShowRx').checked)continue;selectionLine([...points,points[0]],palette[id]);selectionFace(points,palette[id]);}if(model.scan_fan.columns[slot])selectionLine([model.scan_fan.origin,model.scan_fan.columns[slot].point],palette.scan);}
 else{selectionLine(model.views.channels[channel].full_band,palette.target,1);if(column)for(const id of ['tx','rx']){if(!$(id==='tx'?'sceneShowTx':'sceneShowRx').checked)continue;const points=column[id+'_corners'];selectionLine([...points,points[0]],palette[id]);selectionFace(points,palette[id],.35);selectionLine([model.origin,points[0]],palette[id],.5);selectionLine([model.origin,points[3]],palette[id],.5);}}
 if(c.detector_corners)selectionLine([...c.detector_corners,c.detector_corners[0]],palette.detector);
 $('sceneSelectionNote').textContent='V'+channel+' / '+model.channel_regions.length+' · 列 '+slot+' / '+model.slot_count+(model.scan_fan.columns[slot]?' · H中心 '+fmt(model.scan_fan.columns[slot].h_mrad)+' mrad':'')+' · '+(scope==='overview'?'整帧视场':'局部放大');$('sceneCenterAnglesDeg').textContent='等价中心角：'+(model.scan_fan.columns[slot]?'H '+fmt(model.scan_fan.columns[slot].h_deg)+' / ':'')+'V '+fmt(model.views.channels[channel].v_center_deg)+' deg';renderDetails();render();}
function svg(body,label){return '<svg viewBox="0 0 332 172" role="img" aria-label="'+label+'">'+body+'</svg>';}
function renderDetails(){const d=model.views,c=d.channels[channel],p=d.local,column=d.column_regions[Number($('sceneSlot').value)];
 let full='<rect x="34" y="24" width="264" height="116" class="detail-frame"/>';
 for(const row of d.chart.channels)full+=`<rect x="34" y="${row.y}" width="264" height="${row.height}" class="detail-row" data-channel="${row.index}" role="button" tabindex="0" aria-label="选择V${row.index}角通道"/>`;
 for(const col of d.chart.columns)full+=`<path d="M${col.x} 24V140" class="detail-grid"/>`;
 full+=`<rect x="34" y="${c.full_chart_y}" width="264" height="${c.full_chart_height}" class="detail-selected-row"/>`;
 if(column)full+=`<path d="M${column.chart_x} 24V140" class="detail-selected-column"/>`;
 full+=`<text x="34" y="158">−H</text><text x="245" y="158">+H →</text><text x="8" y="20">+V</text><text x="4" y="144">−V</text><text x="108" y="16">${fmt(d.hfov_deg)} × ${fmt(d.vfov_deg)} deg</text>`;
 for(let i=0;i<=4;i++){const hv=-d.hfov_deg/2+d.hfov_deg*i/4,vv=-d.vfov_deg/2+d.vfov_deg*i/4;full+=`<text x="${34+264*i/4}" y="168" text-anchor="middle">${fmt(hv)}</text><text x="30" y="${140-116*i/4+3}" text-anchor="end">${fmt(vv)}</text>`;}
 $('sceneFullChart').innerHTML=svg(full,'整机HFOV与VFOV、当前列和V通道');for(const e of $('sceneFullChart').querySelectorAll('[data-channel]')){e.onclick=()=>{channel=Number(e.dataset.channel);$('sceneChannel').value=String(channel);pause();updateChannel();};e.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();e.onclick();}};}
 const rect=(r,id)=>`<rect x="${r[0]}" y="${r[1]}" width="${r[2]}" height="${r[3]}" class="detail-domain ${id}"/>`;

 $('sceneAngleNote').textContent='等价 deg：Tx H '+fmt(p.tx_h_deg)+' / V '+fmt(p.tx_v_deg)+'；Rx H '+fmt(p.rx_h_deg)+' / V '+fmt(p.rx_v_deg);
 $('sceneMismatch').textContent=d.explanation+' 整列V包络：Tx '+fmt(d.tx_v_envelope_mrad)+' / Rx '+fmt(d.rx_v_envelope_mrad)+' mrad。';$('sceneMismatch').classList.toggle('different',!d.same_v_width);$('sceneFollowRx').disabled=d.rx_v_follows_tx;
 let localAxes=`<path d="M50 25V140H318" class="detail-axis"/><path d="M184 25V140M50 82.5H318" class="detail-grid"/>`;for(const tick of p.ticks_h)localAxes+=`<path d="M${tick.x} 140v5" class="detail-axis"/><text x="${tick.x}" y="158" text-anchor="middle">${fmt(tick.value)}</text>`;for(const tick of p.ticks_v)localAxes+=`<path d="M45 ${tick.y}H50" class="detail-axis"/><text x="42" y="${tick.y+4}" text-anchor="end">${fmt(tick.value)}</text>`;
 $('sceneLocalChart').innerHTML=diagram(`${rect(p.tx_rect,'tx')}${rect(p.rx_rect,'rx')}${localAxes}<text x="15" y="197">Tx H ${fmt(p.tx_h_mrad)} × V ${fmt(p.tx_v_mrad)} mrad</text><text x="15" y="217">Rx H ${fmt(p.rx_h_mrad)} × V ${fmt(p.rx_v_mrad)} mrad</text><text x="318" y="178" text-anchor="end">H / mrad →</text><text x="50" y="17">V / mrad ↑</text>`,'底部H轴、左侧V轴的单通道角域对照',230);
 const hp=d.h_profile;let hbody='<path d="M44 25V134H308" class="detail-axis"/><text x="8" y="43">1</text><text x="8" y="137">0</text><text x="44" y="18">相对Tx强度</text>';
 for(const tick of hp.ticks)hbody+=`<path d="M${tick.x} 134v5" class="detail-frame"/><text x="${tick.x}" y="151" text-anchor="middle">${fmt(tick.value)}</text>`;
 for(const r of hp.neighbors)hbody+=rect(r,'tx neighboring');hbody+=rect(hp.rx_rect,'rx dashed');hbody+=`<polyline points="${hp.tx_path.map(v=>v.join(',')).join(' ')}" class="detail-tx-line"/><path d="M${hp.step_bracket[0]} 173v8M${hp.step_bracket[0]} 177H${hp.step_bracket[1]}M${hp.step_bracket[1]} 173v8" class="detail-axis"/><text x="176" y="198" text-anchor="middle">ΔH列间距 ${fmt(hp.step_mrad)} mrad</text><text x="253" y="167">H / mrad →</text>`;
 $('sceneHorizontalChart').innerHTML=diagram(hbody,'Tx/Rx水平角宽与扫描列间距对照',210);$('sceneHorizontalNote').textContent='Tx H '+fmt(p.tx_h_mrad)+' / Rx H '+fmt(p.rx_h_mrad)+' mrad；Rx角宽 / ΔH = '+fmt(hp.rx_to_step_ratio)+'。淡框为相邻列Tx；角宽比不是独立分辨单元数。';
 const vp=d.v_profile;let vb='<path d="M58 20V174H292" class="detail-axis"/><text x="12" y="14">+V / mrad</text><text x="210" y="194">相对Tx强度 →</text>';
 for(const tick of vp.ticks)vb+=`<path d="M53 ${tick.y}H292" class="detail-grid"/><text x="48" y="${tick.y+4}" text-anchor="end">${fmt(tick.value)}</text>`;
 vb+=rect(vp.tx_rect,'tx');vb+=rect(vp.rx_envelope,'rx dashed');for(const r of vp.rx_channels)vb+=rect(r,'rx');vb+='<text x="68" y="188">0</text><text x="234" y="188">1</text>';$('sceneVerticalChart').innerHTML=diagram(vb,'Tx均匀V角分布与Rx整列包络',210);
 let image='<path d="M54 28V158M282 28V158M54 96H282" class="detail-axis"/><path d="M54 28L172 96L282 158M54 158L172 96L282 28" class="detail-grid ray-guide"/><ellipse cx="172" cy="96" rx="9" ry="62" class="detail-lens"/><text x="26" y="18">视场 V</text><text x="150" y="18">Rx光学</text><text x="259" y="18">SPAD Y</text><text x="8" y="42">+V↑</text><text x="288" y="42">+Y↑</text>';
 for(const row of d.chart.channels){const ry=28+row.index*130/model.channel_regions.length;image+=`<rect x="275" y="${158-(row.index+1)*130/model.channel_regions.length}" width="14" height="${130/model.channel_regions.length*.75}" class="detail-pixel"/>`;}
 const ty=28+(c.target_y-28)*130/108,iy=28+(c.detector_y-28)*130/108;
 image+=`<path d="M54 ${ty}L172 96L282 ${iy}" class="detail-ray"/><circle cx="54" cy="${ty}" r="4" class="detail-dot"/><rect x="272" y="${iy-4}" width="20" height="8" class="detail-selected-pixel"/><text x="58" y="${ty-9}">V${channel} · ${fmt(c.v_center_mrad)} mrad</text><text x="197" y="${iy-9}">SPAD组 ${c.detector_group}</text><text x="4" y="63">${fmt(d.tx_v_envelope_mrad/2)}</text><text x="4" y="156">${fmt(-d.tx_v_envelope_mrad/2)}</text><text x="291" y="63">${fmt(d.detector_half_height_um)}</text><text x="291" y="156">${fmt(-d.detector_half_height_um)}</text><text x="35" y="182">mrad</text><text x="267" y="182">μm</text><text x="28" y="205">+V映射到−Y · 角度与像面轴分别缩放</text>`;
 $('sceneImageChart').innerHTML=diagram(image,'带坐标的V视场、Rx光学和SPAD倒置映射',218);
}
function diagram(body,label,height){return '<svg viewBox="0 0 350 '+height+'" role="img" aria-label="'+label+'">'+body+'</svg>';}

function updateLabels(){const occupied=[];for(const l of [...labels].sort((a,b)=>(b.id===selected)-(a.id===selected))){const p=l.position.clone().project(camera);l.el.hidden=p.z>1||p.z< -1||p.x< -1||p.x>1||p.y< -1||p.y>1;if(l.el.hidden)continue;const w=l.el.offsetWidth,h=l.el.offsetHeight;const x=Math.max(w/2+8,Math.min(host.clientWidth-w/2-8,(p.x*.5+.5)*host.clientWidth));let y=Math.max(h/2+8,Math.min(host.clientHeight-h/2-55,(-p.y*.5+.5)*host.clientHeight));for(let n=0;n<8;n++){if(!occupied.some(r=>Math.abs(r.x-x)<(r.w+w)/2+5&&Math.abs(r.y-y)<(r.h+h)/2+5))break;y-=h+7;if(y<h/2+8)y=host.clientHeight-h/2-60;}l.el.style.left=x+'px';l.el.style.top=y+'px';l.el.classList.toggle('selected',l.id===selected);occupied.push({x,y,w,h});}}
function render(){if(!renderer||!visible)return;renderer.render(scene,camera);updateLabels();}
function resize(){if(!renderer)return;const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);if(camera.isOrthographicCamera){const span=Math.max(16,16/(w/h));camera.left=-span*w/h/2;camera.right=span*w/h/2;camera.top=span/2;camera.bottom=-span/2;}else camera.aspect=w/h;camera.updateProjectionMatrix();render();}
function applyVisibility(){if(!root)return;root.traverse(o=>{const id=o.userData.component;if(id==='tx')o.visible=$('sceneShowTx').checked;if(id==='rx')o.visible=$('sceneShowRx').checked;});}
function paintSelection(){for(const m of materials){const active=m.userData.id===selected;m.opacity=m.userData.baseOpacity*(active?1:.48);m.transparent=true;if(active&&m.userData.baseOpacity<.1)m.opacity=.13;}
 for(const b of $('sceneParts').children)b.setAttribute('aria-pressed',String(b.dataset.component===selected));render();}
function relatedInputs(component){return [...document.querySelectorAll('[data-path]')].filter(el=>component.paths.some(p=>el.dataset.path===p||el.dataset.path.startsWith(p+'.')));}
function focusInput(el){const d=el.closest('details');if(d)d.open=true;el.scrollIntoView({block:'nearest',behavior:'smooth'});el.focus({preventScroll:true});}
function choose(id,focusForm=false){if(!model)return;if(focusForm)pause();const c=model.components.find(c=>c.id===id);if(!c)return;selected=id;
 $('sceneStep').textContent=stale?'显示上次有效配置 · 当前表单待计算':'参数联动 · '+id.toUpperCase();$('sceneTitle').textContent=c.title;$('sceneDescription').textContent=c.description;
 $('sceneFacts').replaceChildren();for(const fact of c.facts){const row=document.createElement('div');row.className='scene-fact';const label=document.createElement('span');label.textContent=fact.label;const value=document.createElement('strong');value.textContent=fmt(fact.value)+' '+fact.unit;row.append(label,value);$('sceneFacts').append(row);}
 document.querySelectorAll('.scene-linked').forEach(e=>e.classList.remove('scene-linked'));const inputs=relatedInputs(c);for(const el of inputs)el.classList.add('scene-linked');$('sceneParamLinks').replaceChildren();for(const el of inputs.slice(0,5)){const b=document.createElement('button');b.type='button';b.textContent=el.getAttribute('aria-label');b.onclick=()=>focusInput(el);$('sceneParamLinks').append(b);}
 if(focusForm){document.querySelector('.scene-inspector').scrollTop=0;if(inputs[0])focusInput(inputs[0]);}paintSelection();
}
function pathSelected(path){if(!model)return;let best=null,length=-1;for(const c of model.components)for(const p of c.paths)if((path===p||path.startsWith(p+'.'))&&p.length>length){best=c.id;length=p.length;}if(best){pause();choose(best);}}
function viewAt(name){view=name;for(const b of document.querySelectorAll('[data-scene-view]'))b.setAttribute('aria-pressed',String(b.dataset.sceneView===name));camera=['front','top','side'].includes(name)?orthographicCamera:perspectiveCamera;controls.object=camera;resize();camera.up.set(0,name==='top'?0:1,name==='top'?1:0);camera.position.fromArray(positions[name]);controls.target.fromArray(lookAt[name]);if(camera.isPerspectiveCamera&&name==='perspective'){const factor=Math.max(1,1.25/camera.aspect);camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);}controls.update();render();}
function pause(){playing=false;cancelAnimationFrame(frame);frame=0;if(packet)packet.visible=false;$('scenePlay').textContent='▶ 传播示意';$('scenePlay').setAttribute('aria-pressed','false');if(model)$('sceneAnimation').textContent=stale?'参数已改：等待有效计算后更新三维图':'拖动旋转 · 滚轮缩放 · 点击部件查看含义';render();}
function animate(now){if(!playing||!visible||document.hidden)return;const dt=lastTime?(now-lastTime)/1000:0;lastTime=now;phase=(phase+Math.min(dt,.1)/4.8)%1;
 const path=model.channel_regions[channel].animation_path;const segment=phase*(path.length-1),index=Math.floor(segment),t=segment-index;packet.visible=index<2||model.return_path_available;packet.position.fromArray(path[index]).lerp(new THREE.Vector3(...path[index+1]),t);packet.material.color.set(index<2?palette.tx:palette.rx);
 const stages=['光源输出 → 角度原点','照明沿Tx角域到达目标','目标回波 → 角度原点','Rx接收 → 入瞳','接收光 → SPAD探测面'];
 $('sceneAnimation').textContent='讲解动画 · '+stages[index]+(model.return_path_available?'':'（当前采样角无Tx/Rx重叠，不画回波）');
 if(index!==lastStage){lastStage=index;choose(['source','tx','rx','rx','detector'][index]);}
 render();frame=requestAnimationFrame(animate);
}
function togglePlay(){if(scope==='overview'&&!playing){scope='local';for(const b of document.querySelectorAll('[data-scene-scope]'))b.setAttribute('aria-pressed',String(b.dataset.sceneScope===scope));rebuild();choose(selected);}if(playing){pause();return;}if(!model||stale||!model.animation_allowed)return;playing=true;phase=0;lastTime=0;lastStage=-1;$('scenePlay').textContent='Ⅱ 暂停动画';$('scenePlay').setAttribute('aria-pressed','true');frame=requestAnimationFrame(animate);}
function update(payload){if(!payload?.schematic)return;try{pause();if(!model)channel=Math.floor(payload.schematic.channel_regions.length/2);model=payload.schematic;channel=Math.min(channel,model.channel_regions.length-1);$('sceneChannel').replaceChildren();for(const c of model.channel_regions){const o=document.createElement('option');o.value=String(c.index);o.textContent='V'+c.index;$('sceneChannel').append(o);}$('sceneChannel').value=String(channel);$('sceneSlot').max=model.slot_count-1;if(!$('sceneSlot').value||Number($('sceneSlot').value)>=model.slot_count)$('sceneSlot').value=String(Math.floor(model.slot_count/2));stale=false;$('sceneAnimation').textContent='拖动旋转 · 滚轮缩放 · 点击部件查看含义';panel.classList.remove('scene-stale');$('sceneState').textContent='当前配置 · '+payload.fingerprint.slice(0,10);$('sceneScope').textContent=model.note;
 $('sceneScale').textContent=`角域横向放大 ${fmt(model.scale.angular_exaggeration)} 倍（相对纵深，H/V同比例）。${model.density_label}。${model.display_notes.join(' ')} 整帧视场使用柱面角坐标示意，V方向放大 ${fmt(model.views.vertical_exaggeration)} 倍；下方单通道图H/V同比例。`;
 $('sceneParts').replaceChildren();for(const c of model.components){const b=document.createElement('button');b.type='button';b.dataset.component=c.id;b.textContent=({source:'光源',tx:'Tx角域',rx:'Rx收光',detector:'SPAD',target:'目标',scan:'转镜'})[c.id];b.onclick=()=>choose(c.id,true);$('sceneParts').append(b);}
 rebuild();choose(selected);$('scenePlay').disabled=!model.animation_allowed;if(!model.animation_allowed)$('sceneAnimation').textContent='光源功率为0：保留角分布形状，关闭传播动画。';}catch(e){fail(e);}}
function markStale(){stale=true;pause();panel.classList.add('scene-stale');$('sceneState').textContent='参数已改 · 显示上次有效配置';$('scenePlay').disabled=true;if(model)choose(selected);}
try{
 setPalette();renderer=new THREE.WebGLRenderer({canvas:$('sceneCanvas'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));scene=new THREE.Scene();perspectiveCamera=new THREE.PerspectiveCamera(42,1,.1,150);orthographicCamera=new THREE.OrthographicCamera(-8,8,8,-8,.1,150);camera=perspectiveCamera;controls=new OrbitControls(camera,renderer.domElement);controls.minDistance=3;controls.maxDistance=45;controls.enableDamping=false;controls.addEventListener('change',render);viewAt(view);resize();
 let down;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const rect=renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.params.Line.threshold=.12;ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObjects(pickables).find(h=>h.object.visible);if(hit)choose(hit.object.userData.component,true);});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();fail('WebGL上下文丢失，请刷新页面恢复');});
 new ResizeObserver(resize).observe(host);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible){render();if(playing){lastTime=0;cancelAnimationFrame(frame);frame=requestAnimationFrame(animate);}}else cancelAnimationFrame(frame);}).observe(host);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(frame);else if(playing&&visible){lastTime=0;frame=requestAnimationFrame(animate);}});
 document.addEventListener('focusin',e=>{if(e.target.dataset?.path||e.target.dataset?.focusPath)pathSelected(e.target.dataset.path||e.target.dataset.focusPath);else{const curve=e.target.closest?.('[id^="curve-"]');if(curve)pathSelected('system.spectral_inputs.'+curve.id.slice(6));}});
 $('sceneChannel').onchange=()=>{channel=Number($('sceneChannel').value);pause();updateChannel();choose('detector');};$('sceneSlot').oninput=()=>{if(!Number.isInteger(Number($('sceneSlot').value))||Number($('sceneSlot').value)<0||Number($('sceneSlot').value)>=model.slot_count){$('sceneSlot').setCustomValidity('选择有效的点云列索引');return;}$('sceneSlot').setCustomValidity('');updateChannel();choose('scan');};for(const button of document.querySelectorAll('[data-detail-target]'))button.onclick=()=>{const inspector=document.querySelector('.scene-inspector'),target=$(button.dataset.detailTarget);target.scrollIntoView({block:'center',behavior:'smooth'});};$('sceneFollowRx').onclick=()=>document.getElementById('followRxV').click();for(const b of document.querySelectorAll('[data-scene-scope]'))b.onclick=()=>{scope=b.dataset.sceneScope;for(const other of document.querySelectorAll('[data-scene-scope]'))other.setAttribute('aria-pressed',String(other===b));pause();rebuild();choose(selected);viewAt('perspective');};$('scenePlay').onclick=togglePlay;$('sceneReset').onclick=()=>viewAt('perspective');for(const b of document.querySelectorAll('[data-scene-view]'))b.onclick=()=>viewAt(b.dataset.sceneView);for(const id of ['sceneShowTx','sceneShowRx'])$(id).onchange=()=>{applyVisibility();updateChannel();render();};
 window.addEventListener('lidar-theme-change',()=>{if(model){rebuild();choose(selected);}else setPalette();});
 window.addEventListener('budget-scene-update',e=>update(e.detail));window.addEventListener('budget-scene-stale',markStale);window.addEventListener('beforeunload',()=>{pause();disposeRoot();controls.dispose();renderer.dispose();});
 if(window.budgetScenePayload)update(window.budgetScenePayload);
}catch(e){fail(e);}
