'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v===null||v===undefined?'待提供 / 未评估':typeof v==='number'?v.toLocaleString('zh-CN',{maximumSignificantDigits:6}):String(v);
const get=(o,p)=>p.split('.').reduce((v,k)=>v[k],o);
const put=(o,p,v)=>{const ks=p.split('.');const k=ks.pop();get(o,ks.join('.'))[k]=v;};
const clone=o=>structuredClone(o);
const KEY='spad-hardware-budget-v1';
let catalog,config,editors,result=null,baseline=null,timer,revision=0,running=false,queued=false;
const enumNames={gaussian:'高斯',rectangular:'矩形脉冲',rectangle:'矩形孔径',circle:'圆形孔径',ellipse:'椭圆孔径',true:'开启',false:'关闭'};
const metricDefs={pulse_average_power_w:['单脉冲等效平均功率 · Tx前','W'],single_pulse_energy_nj:['派生单发能量 · Tx前','nJ'],vfov_deg:['垂直视场VFOV','deg'],vertical_angle_step_deg:['V等角预算分区宽度','deg'],column_time_us:['每列可用时间','μs'],time_margin_us:['计入复位后余量','μs'],column_energy_nj:['每列光能 · Tx前','nJ'],average_optical_power_w:['整帧平均光功率 · Tx前','W'],acquisition_envelope_us:['多发接收包络','μs'],margin_without_reset_us:['未计复位时间余量','μs'],max_pulses_per_column:['时间容量最大发数','发/列'],max_frame_rate_hz:['时间容量最高帧率','Hz'],angle_step_deg:['水平采样间隔','deg'],required_optical_rad_s:['匀速扫描光学角速度','rad/s'],pulse_train_sweep_mrad:['首末发射角位移','mrad'],return_rotation_mrad:['飞行期间光学转角','mrad'],flight_ns:['物理往返飞行时间','ns'],gate_fraction:['单发门内光学份额','1'],pulse_count:['每列发数','发'],pulses_per_second:['平均发射次数','发/s'],average_output_power_w:['平均光功率 · Tx后','W'],peak_optical_power_w:['峰值光功率 · Tx前','W'],electric_power_w:['发光器件电输入估算','W'],emitter_heat_w:['发光器件非光损耗','W'],signal_candidates_per_column:['门内信号候选 / 列','次'],background_candidates_per_column:['光学背景候选 / 列','次'],device_noise_candidates_per_column:['器件噪声候选 / 列','次'],final_mixed_records:['最终混合记录','未仿真'],channels:['读出通道数','通道'],spads_per_channel:['H × V 聚合','SPAD/通道'],physical_spads:['物理阵列规模','SPAD'],histogram_bins:['每通道时间分箱','bin'],histogram_body_bytes:['直方图计数区','byte/列'],histogram_payload_bytes:['直方图含列头','byte/列'],average_payload_mbps:['平均净载荷需求','Mbps'],wire_time_us:['直方图单列传输','μs']};
async function request(url,body,text=false){const r=await fetch(url,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':text?'text/plain':'application/json'},body:text?body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail));return d;}
function fail(e){$('error').hidden=false;$('error').textContent=e.message||String(e);}
function envelope(c){return {schema_version:2,kind:'hardware-budget',experiment:c};}
function download(name,obj){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
function fieldSchema(path){let s=catalog.schema;for(const part of path.split('.')){if(s.$ref)s=catalog.schema.$defs[s.$ref.split('/').pop()];s=s.properties[part];}return s;}
function helpIndex(tree,out={}){for(const [k,v]of Object.entries(tree)){if(v&&typeof v==='object'){if(v.label)out[k]=v;else helpIndex(v,out);}}return out;}
function buildForm(){const help=helpIndex(catalog.help);for(const [i,[title,prefix,keys]]of catalog.groups.entries()){const d=document.createElement('details');d.open=i<4;const summary=document.createElement('summary');summary.textContent=title;d.append(summary);const grid=document.createElement('div');grid.className='field-grid';for(const key of keys){const path=prefix+'.'+key;const schema=fieldSchema(path);const kinds=schema.anyOf||[schema];const spec=kinds.find(k=>k.type!=='null');const nullable=kinds.some(k=>k.type==='null');let meta=help[path]||help[(prefix==='targets'?'system_targets':prefix.replace(/^system\./,''))+'.'+key]||help[key];if(!meta)throw Error('缺少参数说明：'+path);const wrap=document.createElement('div');wrap.className='field';const label=document.createElement('label');label.htmlFor='f-'+path;label.textContent=meta.label;const unit=document.createElement('small');unit.textContent=meta.unit;label.append(' ',unit);wrap.title=meta.description;const input=document.createElement(spec.enum||spec.type==='boolean'?'select':'input');input.id='f-'+path;input.dataset.path=path;input.dataset.kind=spec.type;input.dataset.nullable=String(nullable);input.setAttribute('aria-label',meta.label);if(input.tagName==='SELECT'){for(const value of spec.enum||(spec.type==='boolean'?['true','false']:[])){const option=document.createElement('option');option.value=String(value);option.textContent=enumNames[value]||value;input.append(option);}}else{input.type='number';input.step=spec.type==='integer'?'1':'any';input.placeholder=nullable?'待提供':'必填';if(spec.minimum!==undefined)input.min=spec.minimum;if(spec.maximum!==undefined)input.max=spec.maximum;}input.addEventListener('change',changed);wrap.append(label,input);grid.append(wrap);}d.append(grid);$('fields').append(d);}
for(const [k,meta]of Object.entries(catalog.curves.groups)){const d=document.createElement('details');const sum=document.createElement('summary');sum.textContent=meta.label;const root=document.createElement('div');root.id='curve-'+k;d.append(sum,root);$('curves').append(d);}editors=new CurveEditors(catalog.curves,changed,(k,s)=>request('/api/curve/validate?kind='+k,s));}
function fill(c){config=clone(c);for(const e of document.querySelectorAll('[data-path]')){const v=get(c,e.dataset.path);e.value=v===null?'':String(v);}editors.fill(c.system.spectral_inputs);visibility();}
function collect(){const c=clone(config);for(const e of document.querySelectorAll('[data-path]')){let v=e.value;if(v===''){if(e.dataset.nullable==='true')v=null;else throw Error(e.getAttribute('aria-label')+'不能为空');}else if(e.dataset.kind==='boolean')v=v==='true';else if(e.dataset.kind==='integer'||e.dataset.kind==='number'){v=Number(v);if(!Number.isFinite(v))throw Error('参数必须为有限数');if(e.dataset.kind==='integer'&&!Number.isInteger(v))throw Error(e.getAttribute('aria-label')+'必须为整数');}put(c,e.dataset.path,v);}c.system.spectral_inputs=editors.values();return c;}
function visibility(){const prbs=$('f-assumptions.prbs_enabled').value==='true';for(const k of ['prbs_chip_count','prbs_chip_ns','prbs_on_count'])$('f-assumptions.'+k).closest('.field').classList.toggle('inactive',!prbs);const shape=$('f-system.rx.rx_aperture_shape').value;for(const key of ['rx_aperture_mm','rx_aperture_width_mm','rx_aperture_height_mm'])$('f-system.rx.'+key).closest('.field').classList.toggle('inactive',key==='rx_aperture_mm'?shape!=='circle':shape==='circle');}
function save(c){localStorage.setItem(KEY,JSON.stringify({draft:envelope(c),baseline}));}
function changed(){revision++;visibility();$('resultState').textContent='参数已改 · 结果待更新';$('formState').textContent='草稿已修改；下方保留上次有效预算。';$('pin').disabled=true;$('sendB').disabled=true;try{save(collect());}catch(e){fail(e);return;}clearTimeout(timer);timer=setTimeout(calculate,catalog.algorithms.parameter_preview_debounce_ms);}
async function calculate(){if(running){queued=true;return;}clearTimeout(timer);let draft;try{draft=collect();}catch(e){fail(e);return;}const rev=revision;running=true;$('calculate').disabled=true;$('pin').disabled=true;$('sendB').disabled=true;$('resultState').textContent='正在计算 · 结果待更新';$('formState').textContent='正在计算静态光学与系统预算…';try{const next=await request('/api/system-budget/calculate',draft);if(rev!==revision){queued=true;return;}result=next;config=clone(next.configuration.experiment);$('error').hidden=true;$('resultState').textContent='当前参数 · 已计算';$('formState').textContent='计算完成；功率×脉宽换算单发能量，Rx角域独立。';$('pin').disabled=false;$('sendB').disabled=false;render();save(config);}catch(e){fail(e);$('resultState').textContent='计算失败 · 保留旧结果';$('formState').textContent='当前参数无有效预算，请修正错误。';$('pin').disabled=true;$('sendB').disabled=true;}finally{running=false;$('calculate').disabled=false;if(queued){queued=false;calculate();}}}
function cards(keys){return keys.map(k=>`<div class="metric"><div class="label">${metricDefs[k][0]}</div><div class="value">${fmt(result.metrics[k])}</div><div class="unit">${metricDefs[k][1]}</div></div>`).join('');}
function facts(keys){return keys.map(k=>`<div class="fact">${metricDefs[k][0]}<strong>${fmt(result.metrics[k])} <small>${metricDefs[k][1]}</small></strong></div>`).join('');}
function latex(el,source){try{katex.render(source,el,{displayMode:true,throwOnError:true});}catch(e){el.textContent='公式渲染失败：'+e.message+'\n'+source;el.dataset.formulaError='true';}}
function formulas(root,items){root.replaceChildren();for(const f of items){const box=document.createElement('div');box.className='formula';if(f.title){const h=document.createElement('h3');h.textContent=f.title;box.append(h);}const math=document.createElement('div');latex(math,f.latex);box.append(math);const p=document.createElement('p');p.className='note';p.textContent=f.note||f.symbols;box.append(p);if(f.values){const table=document.createElement('table');table.innerHTML=f.values.map(v=>`<tr><td>${esc(v.label)}</td><td>${fmt(v.value)}</td><td>${esc(v.unit)}</td></tr>`).join('');box.append(table);}root.append(box);}}
function timeline(){const t=result.timing;const w=920,left=82,right=25,rowHeight=24,h=80+t.rows.length*rowHeight;const scale=v=>left+v/t.plot_end_ns*(w-left-right);let parts=`<defs><pattern id="resetHatch" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="#748393"/></pattern></defs>`;for(let i=0;i<=4;i++){const v=t.plot_end_ns*i/4;parts+=`<line x1="${scale(v)}" y1="28" x2="${scale(v)}" y2="${h-30}" stroke="#2c3d4b"/><text x="${scale(v)}" y="18" fill="#9bafbe" font-size="11" text-anchor="middle">${fmt(v/1000)} μs</text>`;}if(t.reset_ns!==null)parts+=`<rect x="${scale(t.envelope_ns)}" y="28" width="${scale(t.envelope_ns+t.reset_ns)-scale(t.envelope_ns)}" height="${h-58}" fill="url(#resetHatch)"/>`;for(const [i,r]of t.rows.entries()){const y=42+i*rowHeight;parts+=`<text x="8" y="${y+4}" fill="#bdcddd" font-size="12">第 ${r.pulse} 发</text><rect x="${scale(r.gate_start_ns)}" y="${y-7}" width="${Math.max(1,scale(r.gate_end_ns)-scale(r.gate_start_ns))}" height="14" fill="#78aafa" opacity=".45"/><circle cx="${scale(r.emission_ns)}" cy="${y}" r="3" fill="#59d9cc"/><path d="M${scale(r.return_ns)} ${y-5}l5 5-5 5-5-5z" fill="#f4b46d"/>`;}
parts+=`<line x1="${scale(t.slot_max_ns)}" y1="25" x2="${scale(t.slot_max_ns)}" y2="${h-26}" stroke="#fa8895" stroke-dasharray="4 4"/><text x="${scale(t.slot_max_ns)-4}" y="${h-8}" text-anchor="end" fill="#fa8895" font-size="11">列末 ${fmt(t.slot_max_ns/1000)} μs</text>`;$('timeline').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="多发接收时序，横轴微秒">${parts}</svg>`;$('timingNote').textContent=`从首发中心起计；${t.reset_ns===null?'复位耗时未知，未画成零时长。':'复位安排在接收包络结束之后。'} ${t.truncated?'仅显示前'+t.rows.length+'发；计算包含全部发数。':''} 扫描位移是匀速预算，未用于修正下方静态光子数。`;
}
function photonChart(){const b=result.optical_budget;$('spectralBand').textContent='背景原始光子积分波段：'+b.background_integration_band_nm.map(fmt).join('–')+' nm；背景按独立Rx收光角域积分。';const rows=[['单发信号 · 入瞳',b.signal_rx_incident_photons_per_pulse,'#59d9cc'],['单发信号 · 探测面',b.signal_sensor_incident_photons_per_pulse,'#59d9cc'],['单发信号 · 候选雪崩',b.signal_candidate_avalanches_per_pulse,'#59d9cc'],['单门太阳 · 候选雪崩',b.solar_candidate_avalanches_per_gate,'#f4b46d'],['单门其他光 · 候选雪崩',b.other_candidate_avalanches_per_gate,'#f4b46d']];const max=Math.max(...rows.map(r=>r[1]));let body='';rows.forEach(([label,value,color],i)=>{const y=28+i*36;const width=max>0?value/max*470:0;body+=`<text x="5" y="${y}" fill="#b7cad8" font-size="12">${label}</text><rect x="210" y="${y-12}" width="${width}" height="16" rx="2" fill="${color}"/><text x="${218+width}" y="${y}" fill="#e2ebf2" font-size="12">${fmt(value)}</text>`;});$('photonChart').innerHTML=`<svg viewBox="0 0 850 190" role="img" aria-label="光子预算线性条形图，单发信号与单门背景口径分别标注">${body}</svg>`;const intro=document.createElement('p');intro.className='note';intro.textContent=result.photon_flow.intro;formulas($('photonFlow'),result.photon_flow.steps);$('photonFlow').prepend(intro);}
function renderPrbs(){const p=result.prbs;if(!p){$('prbs').innerHTML='<p class="note">尚未启用。左侧填写码片数、码片时长及开码片数，可估算独立候选方案的周期、光能与扫描位移。</p>';return;}const fields=[['码周期',p.period_ns,'ns'],['开码片比例',p.on_fraction,'1'],['每码周期能量',p.energy_nj,'nJ'],['码周期平均光功率',p.code_average_power_w,'W'],['名义周期距离',p.nominal_periodic_range_m,'m'],['序列期间扫描位移',p.sweep_mrad,'mrad']];$('prbs').innerHTML='<div class="facts">'+fields.map(([k,v,u])=>`<div class="fact">${k}<strong>${fmt(v)} <small>${u}</small></strong></div>`).join('')+'</div>'+`<p class="note">${esc(p.note)}</p><p class="${p.within_column&&p.pulse_fwhm_within_chip?'note':'orange'}">${p.within_column?'码周期可放入列周期':'码周期超过列周期'}；${p.pulse_fwhm_within_chip?'脉冲FWHM小于码片':'脉冲FWHM不小于码片，短脉冲编码假设不满足'}。</p>`;}
function renderVertical(){const v=result.vertical_budget;if(!v)return;$('verticalNote').textContent=`Tx全宽：H ${fmt(v.tx_h_full_mrad)} mrad / V ${fmt(v.tx_v_full_mrad)} mrad（VFOV）；Rx H [${v.rx_h_bounds_mrad.map(fmt).join(', ')}] mrad / V [${v.rx_v_bounds_mrad.map(fmt).join(', ')}] mrad。${v.note}`;$('verticalTx').innerHTML='<table><thead><tr><th>Tx分区索引</th><th>V角域 / mrad</th><th>归一化份额</th><th>等效平均功率 / W</th><th>单发能量 / nJ</th></tr></thead><tbody>'+v.rows.map(r=>`<tr><td>${r.v_index}</td><td>${fmt(r.angle_low_mrad)} ～ ${fmt(r.angle_high_mrad)}</td><td>${fmt(r.tx_fraction)}</td><td>${fmt(r.tx_pulse_average_power_w)}</td><td>${fmt(r.tx_energy_nj)}</td></tr>`).join('')+'</tbody></table>';$('verticalRx').innerHTML='<table><thead><tr><th>物理V组索引</th><th>探测面光子 / 发</th><th>信号候选 / 列</th><th>背景候选 / 列</th></tr></thead><tbody>'+v.rows.map(r=>`<tr><td>${r.v_index}</td><td>${fmt(r.sensor_photons_per_pulse)}</td><td>${fmt(r.signal_candidates_per_column)}</td><td>${fmt(r.background_candidates_per_column)}</td></tr>`).join('')+'</tbody></table>';}
function flatten(o,p='',out={}){for(const [k,v]of Object.entries(o)){const path=p?p+'.'+k:k;if(v!==null&&typeof v==='object'&&!Array.isArray(v))flatten(v,path,out);else out[path]=JSON.stringify(v);}return out;}
function compare(){if(!baseline){$('comparison').innerHTML='';$('differences').innerHTML='';$('baselineNote').textContent='点击“保存为对比基准”，再修改参数查看变化。';return;}$('baselineNote').textContent=`基准为保存时的计算快照（${baseline.provenance.utc}，版本 ${baseline.provenance.model_version}，指纹 ${baseline.provenance.configuration_sha256.slice(0,12)}）；刷新不会改写基准。`;$('comparison').innerHTML='<table><thead><tr><th>指标</th><th>基准</th><th>当前方案</th><th>单位</th></tr></thead><tbody>'+Object.entries(metricDefs).map(([k,[label,unit]])=>`<tr><td>${label}</td><td>${fmt(baseline.metrics[k])}</td><td class="${baseline.metrics[k]!==result.metrics[k]?'changed':''}">${fmt(result.metrics[k])}</td><td>${unit}</td></tr>`).join('')+'</tbody></table>';const a=flatten(baseline.configuration.experiment),b=flatten(result.configuration.experiment);const diffs=[...new Set([...Object.keys(a),...Object.keys(b)])].filter(k=>a[k]!==b[k]);$('differences').innerHTML=diffs.length?'<table><tr><th>参数路径</th><th>基准</th><th>当前</th></tr>'+diffs.map(k=>`<tr><td>${esc(k)}</td><td>${esc(a[k])}</td><td>${esc(b[k])}</td></tr>`).join('')+'</table>':'<p class="note">输入一致。</p>';}
function render(){$('metrics').innerHTML=cards(['pulse_average_power_w','single_pulse_energy_nj','column_time_us','time_margin_us','column_energy_nj','average_optical_power_w','vfov_deg','vertical_angle_step_deg']);$('photonSummary').innerHTML=cards(['signal_candidates_per_column','background_candidates_per_column','device_noise_candidates_per_column']);$('timeFacts').innerHTML=facts(['acquisition_envelope_us','margin_without_reset_us','max_pulses_per_column','max_frame_rate_hz','angle_step_deg','required_optical_rad_s','pulse_train_sweep_mrad','return_rotation_mrad','gate_fraction']);$('resourceFacts').innerHTML=facts(['peak_optical_power_w','average_output_power_w','electric_power_w','emitter_heat_w','channels','spads_per_channel','physical_spads','histogram_bins','histogram_body_bytes','histogram_payload_bytes','average_payload_mbps','wire_time_us','final_mixed_records']);$('constraints').innerHTML=result.constraints.map(c=>`<div class="check"><span class="state ${c.status}">${({pass:'满足',fail:'超限',unknown:'待确认',review:'需验证'})[c.status]}</span><strong>${esc(c.label)}</strong><p>${esc(c.detail)}</p></div>`).join('');$('stamp').textContent=`${result.provenance.utc} · 模型 ${result.provenance.model_version} · 配置 ${result.provenance.configuration_sha256.slice(0,16)} · 当前构造光学默认不代表实物`;timeline();photonChart();renderVertical();renderPrbs();compare();formulas($('formulaList'),result.formulas);$('limitations').innerHTML=result.limitations.map(s=>`<li>${esc(s)}</li>`).join('');$('audit').textContent=JSON.stringify({provenance:result.provenance,configuration:result.configuration},null,2);}
async function init(){catalog=await request('/api/system-budget');buildForm();let initial=catalog.defaults;const saved=localStorage.getItem(KEY);let cacheError=null;if(saved){try{const state=JSON.parse(saved);initial=await request('/api/system-budget/import',JSON.stringify(state.draft),true);if(state.baseline){if(!state.baseline.metrics||!state.baseline.provenance||!state.baseline.configuration)throw Error('基准快照结构不完整');baseline=state.baseline;}}catch(e){localStorage.setItem(KEY+'-rejected',saved);cacheError=new Error('旧草稿无法加载，原内容已保留在恢复副本中；本页使用当前默认值。\n'+e.message);}}fill(initial);await calculate();if(saved&&!cacheError&&JSON.parse(saved).draft.schema_version===1)$('formState').textContent='旧工况已保留原能量和角域迁移为功率输入；使用280W/2mrad新默认请点重新加载默认。';if(cacheError)fail(cacheError);}
$('calculate').onclick=calculate;
$('pin').onclick=()=>{if(!result||running)return;baseline=clone(result);save(collect());compare();};
$('clearBaseline').onclick=()=>{baseline=null;save(collect());compare();};
$('reset').onclick=async()=>{try{catalog=await request('/api/system-budget');fill(catalog.defaults);revision++;await calculate();}catch(e){fail(e);}};
$('loadJson').onclick=()=>{try{$('configJson').value=JSON.stringify(collect(),null,2);}catch(e){fail(e);}};
$('applyJson').onclick=async()=>{try{const c=await request('/api/system-budget/import',JSON.stringify(envelope(JSON.parse($('configJson').value))),true);fill(c);revision++;await calculate();}catch(e){fail(e);}};
$('exportConfig').onclick=()=>{try{download('hardware-budget-config.json',envelope(collect()));}catch(e){fail(e);}};
$('exportResult').onclick=()=>{if(result)download('hardware-budget-snapshot.json',{...result,comparison_baseline:baseline});};
$('importConfig').onchange=async e=>{try{const c=await request('/api/system-budget/import',await e.target.files[0].text(),true);fill(c);revision++;await calculate();}catch(err){fail(err);}finally{e.target.value='';}};
$('sendB').onclick=()=>{if(!result)return;sessionStorage.setItem('lidar-budget-to-system',JSON.stringify({experiment:result.configuration.experiment.system}));location.href='/system';};
init().catch(fail);
