/* Live B workspace. Python owns physics; current previews and immutable acquisitions are separate. */
'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone = value => JSON.parse(JSON.stringify(value));
const get = (object, path) => path.split('.').reduce((v, key) => v?.[key], object);
const set = (object, path, value) => {const parts=path.split('.'), key=parts.pop();parts.reduce((v,k)=>v[k],object)[key]=value;};
const fmt = (n, digits=2) => (Math.abs(Number(n))<.5*10**(-digits)?0:Number(n)).toLocaleString('en-US',{maximumFractionDigits:digits});
const WORKSPACE_KIND=document.body.dataset.lab;
const IS_SCAN=WORKSPACE_KIND==='scan';
const API='/api/experiments/'+WORKSPACE_KIND;
const KEY='spad-'+WORKSPACE_KIND+'-modular-v3';
let data, draft, base, selectedChannels=[0], selectedH, selectedV, windowRange, peakWindow, toastTimer;
let catalog, defaultsForm, previewData, lastResult=null, rawResult=null, currentJob=null, displayedJob=null, editors, previewSerial=0, previewTimer, previewController, pollTimer, loadingConfig=false,viewIsAcquisition=false;
const fieldNames=new Map();
let channelLocator,bMechanism,bHistogram;
const concepts={
 tx:['Tx 发射','单发能量属于配置的 Tx 角域，参考面为 Tx 光学之前。角域内各单元的能量份额归一化、合计为 1，再乘一次 Tx 光学效率；不额外扣除角域外能量。'],
 scene:['场景与传播','当前样例使用同距离、同反射率的扩展朗伯目标，计入大气双程损耗和接收入瞳。场景负责传播，Tx/Rx 分别负责发射与接收光学。'],
 rx:['Rx 成像','构造映射分别使用水平和垂直等效焦距，新工况默认倒置，数据库模式以响应数据为准；所有空间图采用右正左负、上正下负。PSF 再按完整像素积分，得到 PDE/FF 前的入射光子。'],
 spad:['SPAD 物理像素','物理像素是光学映射和器件状态的基本单位。PDE/FF 将入射光子转为候选雪崩，器件死时间决定哪些雪崩能实际发生。'],
 readout:['读出通道','每个通道由一组物理 SPAD 构成。读出逻辑和 TDC 决定最终时间戳；通道编号、像素坐标与角度单元分别管理。']
};
function help(path){return data.help.experiments?.[path]||data.help[path.split('.').at(-1)]||{};}
function numeric(path,label,unit='',wide=false){fieldNames.set(path,label);const h=help(path);return `<label class="field ${wide?'wide':''}" title="${esc(h.description||label)}"><span class="field-title">${esc(label)}</span><span class="input-unit"><input type="number" step="any" data-path="${path}" value="${esc(get(draft,path))}" aria-label="${esc(label)}">${unit?`<span class="unit">${esc(unit)}</span>`:''}</span></label>`;}
function select(path,label,options){fieldNames.set(path,label);return `<label class="field wide" title="${esc(help(path).description||label)}"><span>${label}</span><select data-path="${path}" aria-label="${label}">${options.map(([v,l])=>`<option value="${v}" ${get(draft,path)===v?'selected':''}>${l}</option>`).join('')}</select></label>`;}
function matrix(title,unit,col1,col2,rows){return `<div class="compact-matrix"><div class="matrix-head"><span>${title}</span><span class="unit">${unit}</span></div><div class="matrix-row headers"><span></span><span>${col1}</span><span>${col2}</span></div>${rows.map(([axis,p1,p2])=>`<div class="matrix-row"><span>${axis}</span>${[p1,p2].map((path,i)=>{const label=title+' '+axis+' '+[col1,col2][i];fieldNames.set(path,label);return `<label><input type="number" step="any" data-path="${path}" value="${esc(get(draft,path))}" aria-label="${label}" title="${esc(help(path).description||label)}"></label>`;}).join('')}</div>`).join('')}</div>`;}
function toggle(path,label){fieldNames.set(path,label);return `<label class="toggle-row"><span>${label}</span><span class="switch"><input type="checkbox" data-path="${path}" ${get(draft,path)?'checked':''} aria-label="${label}"></span></label>`;}
function subhead(title){return `<div class="subhead">${title}</div>`;}
function group(id,code,title,summary,body,open=false){return `<details class="parameter-group" data-group="${id}" ${open?'open':''}><summary><span class="group-text"><strong>${title}</strong><small>${summary}</small></span><span class="group-code">${code}</span></summary><div class="group-body">${body}</div></details>`;}
function curveEditor(kind,label){fieldNames.set('spectral_inputs.'+kind,label+'配置');return `<details class="subdetails"><summary>${label}</summary><div class="curve-editor" id="curve-${kind}"></div></details>`;}
function axisPairs(title,rows){return `<div class="compact-matrix axis-pairs"><div class="matrix-head"><span>${title}</span><span class="unit">H / V</span></div><div class="matrix-row headers"><span>参数</span><span>H / x</span><span>V / y</span></div>${rows.map(([label,unit,h,v])=>`<div class="matrix-row"><span>${label}<small>${unit}</small></span>${[h,v].map((path,i)=>{const name=title+' '+label+' '+['H','V'][i];fieldNames.set(path,name);return `<label><input type="number" step="any" data-path="${path}" value="${esc(get(draft,path))}" aria-label="${name}" title="${esc(help(path).description||name)}"></label>`;}).join('')}</div>`).join('')}</div>`;}
function renderParameters(){
 const o=draft.optics,d=draft.device,r=draft.readout,t=draft.timing;
 let opened={};document.querySelectorAll('.parameter-group').forEach(el=>opened[el.dataset.group]=el.open);
 if(!Object.keys(opened).length){try{opened=JSON.parse(localStorage.getItem(KEY+'-open')||'{}');}catch{}}
 const m=(...args)=>matrix(...args),n=(...args)=>numeric(...args),s=(...args)=>select(...args);
 const tx=subhead('光源与发射效率')+`<div class="field-grid">${n('optics.wavelength_nm','激光波长','nm')}${n('optics.pulse_average_power_w','单脉冲等效平均功率 · Tx前','W')}${s('optics.pulse_shape','时间脉冲形状',[['gaussian','高斯脉冲'],['rectangular','矩形脉冲']])}${n('optics.pulse_fwhm_ps','脉宽 FWHM','ps')}${n('optics.tx_efficiency','Tx 光学效率')}</div>`+subhead('发射角分布')+`<div class="field-grid">${s('optics.tx_model','Tx 分布模型',[['gaussian','高斯角分布'],['super_gaussian','超高斯角分布'],['uniform','角域内均匀分布'],['dataset','导入光学数据库']])}</div><div data-visible="tx-gaussian">${m('光束角参数','mrad','角中心','FWHM',[['H','optics.tx_center_h_mrad','optics.tx_fwhm_h_mrad'],['V','optics.tx_center_v_mrad','optics.tx_fwhm_v_mrad']])}</div><div data-visible="tx-super">${axisPairs('H/V 超高斯阶数',[['阶数 m','','optics.tx_order_h','optics.tx_order_v']])}<p class="field-note">m=1 为高斯，指数为 2m；宽度使用上方 FWHM。</p></div><details class="subdetails"><summary>角域与覆盖范围</summary>${m('构造 Tx 角域','mrad','最小值','最大值',[['H','optics.angle_h_min_mrad','optics.angle_h_max_mrad'],['V','optics.angle_v_min_mrad','optics.angle_v_max_mrad']])}<p class="field-note">此角域内份额归一化，E=P等效×脉宽（高斯用FWHM）全部分配到域内；Tx效率另计一次。Rx接收域独立，背景不跟随Tx改变。</p></details><p class="field-note" data-visible="tx-dataset">数据库模式使用文件的角域，Tx 份额在域内归一化；审计保留原始总和，Rx PSF 不补偿边缘损失。</p>`;
 const scene=subhead('目标')+`<div class="field-grid">${n('optics.range_m','目标距离','m')}${n('optics.target_reflectivity','目标反射率')}</div>`+subhead('传播')+`<div class="field-grid">${n('optics.atmospheric_one_way_transmission','单程大气透过率')}${n('optics.overlap_factor','Tx / Rx 重叠因子')}</div>${IS_SCAN?scanMotionFields():'<p class="field-note">当前模型：同距离的扩展朗伯目标。</p>'}`;
 const rx=`<div class="optics-files"><label class="file-button">导入光学数据<input id="importOpticalData" type="file" accept=".json,.yaml,.yml"></label><button id="exportOpticalData" class="text-button">导出当前光学数据</button></div>`+subhead('接收入瞳')+`<div class="field-grid">${s('optics.rx_aperture_shape','入瞳形状',[['rectangle','矩形'],['ellipse','椭圆'],['circle','圆形']])}<div class="field wide" data-visible="aperture-axes">${axisPairs('入瞳全轴尺寸',[['全尺寸','mm','optics.rx_aperture_width_mm','optics.rx_aperture_height_mm']])}</div><div class="field wide" data-visible="aperture-circle">${n('optics.rx_aperture_mm','入瞳直径','mm')}</div></div>`+subhead('位置映射与 PSF')+`<div class="field-grid">${s('optics.rx_model','像面映射模型',[['gaussian_psf','几何映射 + 高斯 PSF'],['super_gaussian_psf','几何映射 + 超高斯 PSF'],['uniform_pixel','均匀像素分配'],['dataset','导入光学数据库']])}<div class="field wide" data-visible="rx-synthetic"><div class="field-grid">${n('optics.rx_efficiency','Rx 收光效率')}${s('optics.mapping_mode','几何映射方向',[['inverted','倒置成像（新工况）'],['legacy_upright','历史正向映射']])}</div></div></div><div data-visible="rx-gaussian">${axisPairs('H/V 成像参数',[['等效焦距','mm','optics.focal_length_h_mm','optics.focal_length_v_mm'],['像面偏移','μm','optics.rx_offset_x_um','optics.rx_offset_y_um']])}${axisPairs('H/V PSF 宽度',[['标准差 σ','μm','optics.psf_sigma_h_um','optics.psf_sigma_v_um']])}<div data-visible="rx-super">${axisPairs('H/V PSF 阶数',[['阶数 m','','optics.psf_order_h','optics.psf_order_v']])}</div><p class="field-note">σ_H / σ_V 是实际标准差；超高斯使用指数 2m，m=1 为高斯。H/V 独立，像面外能量仍保留为损失。</p></div><details class="subdetails" data-visible="rx-synthetic"><summary>构造 Rx 数据库覆盖</summary>${m('Rx 角度覆盖域','mrad','最小值','最大值',[['H','optics.rx_angle_h_min_mrad','optics.rx_angle_h_max_mrad'],['V','optics.rx_angle_v_min_mrad','optics.rx_angle_v_max_mrad']])}</details><p class="field-note" data-visible="rx-dataset">数据库模式使用文件中的实际像素边界、效率与 PSF，构造参数不生效。</p>${curveEditor('filter','滤光片透过率')}`;
 const spad=subhead('像素与探测响应')+`<div class="field-grid"><div data-visible="pixel-pitch">${n('optics.pixel_pitch_um','像素节距','μm')}</div>${n('device.fill_factor','填充因子 FF')}${s('device.detector_operation','SPAD 工作方式',[['gated','仅门内工作'],['free_running','持续工作 / 门内记录']])}</div>${curveEditor('pde','PDE 光谱')}`+subhead('器件噪声与恢复')+`<div class="field-grid">${n('device.dcr_cps_per_spad','暗计数 / SPAD','cps')}${n('device.other_noise_cps_per_spad','其他随机噪声','cps')}${n('device.spad_dead_time_ns','SPAD 死时间','ns')}${n('device.spad_jitter_fwhm_ps','SPAD 抖动 FWHM','ps')}</div>`;
 const modes=Object.entries(data.readout_modes).filter(([k,v])=>k!=='analytic_reference'&&v?.label).map(([k,v])=>[k,v.label]);
 const readout=subhead('通道布局与空间分组')+m('二维布局','个','通道数量','每通道 binning',[['H','optics.channels_h','device.H_binning'],['V','optics.channels_v','device.V_binning']])+`<div class="derived" id="readoutLayoutSummary" aria-live="polite">当前参数布局：等待 Python 校验…</div>`+subhead('电子读出')+`<div class="field-grid">${s('readout.readout_mode','读出架构',modes)}${n('readout.tdc_bin_ps','TDC 时间 bin','ps')}${n('readout.tdc_dead_time_ns','TDC 死时间','ns')}${n('readout.other_jitter_fwhm_ps','电子学抖动 FWHM','ps')}${n('optics.calibration_delay_ns','标定延迟','ns')}</div><details class="subdetails"><summary>TDC 容量与符合逻辑</summary><div class="field-grid">${n('readout.tdc_count','共享 TDC 个数')}${n('readout.tdc_max_hits_per_cycle','每 TDC 记录上限')}${n('readout.or_pulse_width_ns','OR 脉宽','ns')}${n('readout.coincidence_window_ns','符合时间窗','ns')}${n('readout.coincidence_threshold','符合阈值')}</div><p class="field-note">各项仅在所选读出架构适用时生效，详见参数说明。</p></details>`;
 const background=toggle('optics.solar_enabled','太阳光')+`<div data-visible="solar"><div class="field-grid">${n('optics.solar_illuminance_lux','目标面太阳照度','lux')}${n('optics.solar_reflectivity','太阳背景灰反射率')}</div>${curveEditor('solar','太阳光谱')}</div><p class="field-note" data-visible="no-solar">已关闭。开启后配置照度与光谱。</p>`+subhead('其他环境光')+toggle('optics.other_light_enabled','其他环境光')+`<div data-visible="ambient"><div class="field-grid">${n('optics.other_light_scale','环境光强度倍率')}</div>${curveEditor('other','环境光谱')}</div><p class="field-note" data-visible="no-ambient">已关闭。开启后配置强度与光谱。</p>`;
 const acquisition=IS_SCAN?scanAcquisitionFields():subhead('采集时序')+`<div class="field-grid">${n('timing.period_ns','发射周期','ns')}${n('timing.laser_shots','slot 内累计发数 N','发')}${n('timing.gate_start_ns','接收门起点','ns')}${n('timing.gate_width_ns','单 gate 接收门宽','ns')}</div>`+subhead('随机采样与统计')+`<div class="field-grid">${n('rng_seed','随机种子')}${n('timing.monte_carlo_trials','统计重复次数 M','次')}</div><div class="derived">含噪重复采集：<b>${draft.timing.monte_carlo_trials}</b> 次<br>噪声参考：<b>${catalog.algorithms.b_noise_reference==='candidate_scalar'?'解析标量 · 无额外采集':catalog.algorithms.readout_expected_trials+' 次关激光采集'}</b></div><p class="field-note">含噪重复统计包括首次观测；当前噪声参考策略和初始化方式见算法配置。</p>`;
 $('parameterGroups').innerHTML=[...(IS_SCAN?[scanParameterGroup(opened)]:[]),group('tx','TX','Tx 发射',`${o.wavelength_nm} nm · ${o.pulse_average_power_w} W · ${o.tx_model==='gaussian'?'高斯角分布':o.tx_model}`,tx,opened.tx??!IS_SCAN),group('scene','SCENE','场景与传播',`${o.range_m} m · 反射率 ${o.target_reflectivity}`,scene,opened.scene??false),group('rx','RX','Rx 接收光学',`位置映射 · PSF · 滤光片`,rx,opened.rx??false),group('spad','SPAD','SPAD 与阵列',`器件响应 · PDE · 噪声`,spad,opened.spad??false),group('readout','READOUT','读出与分组',`H ${o.channels_h} × V ${o.channels_v} 通道 · 空间 binning`,readout,opened.readout??false),group('background','LIGHT','环境光',`太阳光${o.solar_enabled?'开启':'关闭'} · 其他光${o.other_light_enabled?'开启':'关闭'}`,background,opened.background??false),group('acquisition','ACQ',IS_SCAN?'采集时序':'采集与统计',IS_SCAN?`逐发接收门 · seed ${draft.rng_seed}`:`${t.laser_shots} 发 · seed ${draft.rng_seed}`,acquisition,opened.acquisition??false)].join('');
 document.querySelectorAll('.parameter-group').forEach(el=>el.addEventListener('toggle',saveOpenState));
 editors=new CurveEditors(catalog.curves,()=>{try{draft.spectral_inputs=editors.values();saveDraft();}catch(error){setError(error);queuePreview();}},(kind,source)=>request('/api/curve/validate?kind='+kind,source));editors.fill(draft.spectral_inputs);
 updateVisibility();if(IS_SCAN)updateScanVisibility();markChanges();renderReadoutLayoutSummary();
}
function renderReadoutLayoutSummary(state='ready'){
 const target=$('readoutLayoutSummary');if(!target)return;
 const describe=l=>`<b>${l.pixels_h} × ${l.pixels_v}</b> 物理像素（H × V），<b>${l.total_channels}</b> 个通道；每通道 <b>${l.spads_per_channel}</b> 个 SPAD（${l.binning_h} × ${l.binning_v}）。`;
 const paths=['optics.channels_h','optics.channels_v','device.H_binning','device.V_binning'];
 const matches=previewData&&paths.every(p=>get(previewData.form_configuration,p)===get(draft,p));
 const layout=previewData?.readout_layout;
 target.innerHTML=state==='invalid'?'当前参数布局：输入未通过校验，未更新。':state==='pending'||!matches||!layout?'当前参数布局：等待 Python 校验…':'当前参数布局：'+describe(layout);
 const acquired=lastResult?.readout_layout;
 if(acquired&&(!matches||JSON.stringify(acquired)!==JSON.stringify(layout)))target.innerHTML+='<br><span class="muted">已采集结果仍使用：</span>'+describe(acquired);
}
function updateVisibility(){const checks={'tx-gaussian':['gaussian','super_gaussian'].includes(draft.optics.tx_model),'tx-super':draft.optics.tx_model==='super_gaussian','tx-dataset':draft.optics.tx_model==='dataset','rx-gaussian':['gaussian_psf','super_gaussian_psf'].includes(draft.optics.rx_model),'rx-super':draft.optics.rx_model==='super_gaussian_psf','rx-synthetic':draft.optics.rx_model!=='dataset','rx-dataset':draft.optics.rx_model==='dataset','aperture-axes':draft.optics.rx_aperture_shape!=='circle','aperture-circle':draft.optics.rx_aperture_shape==='circle','solar':draft.optics.solar_enabled,'no-solar':!draft.optics.solar_enabled,'pixel-pitch':draft.optics.rx_model!=='dataset','ambient':draft.optics.other_light_enabled,'no-ambient':!draft.optics.other_light_enabled};document.querySelectorAll('[data-visible]').forEach(el=>el.classList.toggle('hidden',!checks[el.dataset.visible]));const mode=draft.readout.readout_mode;const active={tdc_count:mode==='shared_multitdc',tdc_max_hits_per_cycle:!['independent_first','shared_first'].includes(mode),or_pulse_width_ns:mode.startsWith('shared'),coincidence_window_ns:mode.startsWith('coincidence'),coincidence_threshold:mode.startsWith('coincidence')};for(const [key,shown]of Object.entries(active)){const input=document.querySelector(`[data-path="readout.${key}"]`);if(input)input.closest('label').classList.toggle('hidden',!shown);}}
function saveOpenState(){const open={};document.querySelectorAll('.parameter-group').forEach(el=>open[el.dataset.group]=el.open);localStorage.setItem(KEY+'-open',JSON.stringify(open));}
function changes(){return [...fieldNames].filter(([p])=>JSON.stringify(get(draft,p))!==JSON.stringify(get(lastResult?.form_configuration||defaultsForm,p)));}
function markChanges(){const changed=!!lastResult&&JSON.stringify(draft)!==JSON.stringify(lastResult.form_configuration),custom=JSON.stringify(draft)!==JSON.stringify(defaultsForm);$('draftState').textContent=changed?'参数已改 · 待重新采集':custom?'自定义工况':'初版共有默认值';$('draftState').classList.toggle('amber',changed);$('staleBanner').classList.toggle('hidden',!changed);document.querySelectorAll('[data-path]').forEach(el=>el.classList.toggle('changed',JSON.stringify(get(draft,el.dataset.path))!==JSON.stringify(get(lastResult?.form_configuration||defaultsForm,el.dataset.path))));}
function saveDraft(){localStorage.setItem(KEY,JSON.stringify(draft));markChanges();queuePreview();const o=draft.optics;const summaries={scan:IS_SCAN?`${draft.scan.trajectory} · ${draft.scan.frame_rate_hz} Hz · ${draft.scan.frame_count} 帧`:'',tx:`${o.wavelength_nm} nm · ${o.pulse_average_power_w} W · ${o.tx_model==='gaussian'?'高斯角分布':o.tx_model}`,scene:`${o.range_m} m · 反射率 ${o.target_reflectivity}`,readout:`H ${o.channels_h} × V ${o.channels_v} 通道 · 空间 binning`,background:`太阳光${o.solar_enabled?'开启':'关闭'} · 其他光${o.other_light_enabled?'开启':'关闭'}`,acquisition:IS_SCAN?`逐发接收门 · seed ${draft.rng_seed}`:`${draft.timing.laser_shots} 发 · seed ${draft.rng_seed}`};for(const [id,text]of Object.entries(summaries)){const el=document.querySelector(`[data-group="${id}"] .group-text small`);if(el)el.textContent=text;}}
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),4500);}
function dialog(title,html){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;$('previewDialog').showModal();}
function download(name,dataObject){const blob=new Blob([typeof dataObject==='string'?dataObject:JSON.stringify(dataObject,null,2)],{type:typeof dataObject==='string'?'text/csv;charset=utf-8':'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function color(f){const stops=[[0,[12,32,51]],[.24,[26,79,111]],[.54,[27,145,154]],[.8,[112,211,185]],[1,[249,239,175]]];f=Math.max(0,Math.min(1,f));let i=1;while(i<stops.length-1&&f>stops[i][0])i++;const [a,ca]=stops[i-1],[b,cb]=stops[i];return `rgb(${ca.map((v,k)=>Math.round(v+(cb[k]-v)*(f-a)/(b-a))).join(',')})`;}
function heatmap(id,rows,xedges,yedges,options={}){
 const root=$(id),ny=rows.length,nx=rows[0].length,flat=rows.flat(),max=options.fixedMax??Math.max(...flat),xmin=xedges[0],xmax=xedges.at(-1),ymin=yedges[0],ymax=yedges.at(-1),aspect=(xmax-xmin)/(ymax-ymin),height=options.height||229,plotHeight=height-70,w=Math.min(263,plotHeight*aspect),h=w/aspect,left=42+(263-w)/2,top=25+(plotHeight-h)/2;
 const sx=v=>left+(v-xmin)/(xmax-xmin)*w,sy=v=>top+(ymax-v)/(ymax-ymin)*h;
 const val=v=>options.percent?fmt(v*100,1)+'%':(v!==0&&Math.abs(v)<.01?v.toExponential(1):fmt(v,2));
 let html=`<svg viewBox="0 0 382 ${height}" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="${id}-gradient" x1="0" x2="0" y1="1" y2="0">${[0,.24,.54,.8,1].map(t=>`<stop offset="${t*100}%" stop-color="${color(t)}"/>`).join('')}</linearGradient></defs><text x="${left}" y="14">${esc(options.yLabel||'V · mrad')} ↑</text><text x="321" y="14" style="font-size:8px">${esc(options.colorLabel||'份额')}</text>`;
 rows.forEach((row,y)=>row.forEach((v,x)=>{const label=`H[${x}], V[${y}] · ${xedges[x]}…${xedges[x+1]} / ${yedges[y]}…${yedges[y+1]} · ${v}`;html+=`<rect class="cell" data-x="${x}" data-y="${y}" x="${sx(xedges[x])}" y="${sy(yedges[y+1])}" width="${sx(xedges[x+1])-sx(xedges[x])}" height="${sy(yedges[y])-sy(yedges[y+1])}" fill="${color(max?v/max:0)}" stroke="#0c1c27" stroke-opacity="${options.grid===false?0:.36}" stroke-width=".5" ${options.interactive?`role="button" tabindex="0" aria-label="选择角度 H ${x} V ${y}"`:''}><title>${esc(label)}</title></rect>`;}));
 if(options.groups){const grid=options.form||base,gh=grid.optics.channels_h,gv=grid.optics.channels_v;for(let v=0;v<gv;v++)for(let u=0;u<gh;u++){const x=sx(xedges[u*grid.device.H_binning]),y=sy(yedges[(v+1)*grid.device.V_binning]),ww=sx(xedges[(u+1)*grid.device.H_binning])-x,hh=sy(yedges[v*grid.device.V_binning])-y;html+=`<rect class="channel-frame" x="${x}" y="${y}" width="${ww}" height="${hh}"/><text class="channel-label" x="${x+5}" y="${y+11}">H${u} V${v}</text>`;}}
 if(options.selected){const [x,y]=options.selected;html+=`<rect class="selected-cell" x="${sx(xedges[x])+.7}" y="${sy(yedges[y+1])+.7}" width="${sx(xedges[x+1])-sx(xedges[x])-1.4}" height="${sy(yedges[y])-sy(yedges[y+1])-1.4}"/>`;}
 const xticks=w<110?2:4;for(let i=0;i<=xticks;i++){const x=xmin+(xmax-xmin)*i/xticks;html+=`<text x="${sx(x)}" y="${height-28}" text-anchor="middle">${fmt(x,1)}</text>`;}for(let i=0;i<=4;i++){const y=ymin+(ymax-ymin)*i/4;html+=`<text x="34" y="${sy(y)+3}" text-anchor="end">${fmt(y,1)}</text>`;}
 html+=`<text x="${left+w/2}" y="${height-9}" text-anchor="middle">${esc(options.xLabel||'H · mrad')} →</text><rect x="323" y="${top}" width="10" height="${h}" fill="url(#${id}-gradient)" rx="2"/>`;
 for(let i=0;i<=4;i++)html+=`<text x="339" y="${top+h*i/4+3}" style="font-size:8px">${val(max*(1-i/4))}</text>`;
 root.innerHTML=html+'</svg>';
 root.querySelectorAll('.cell').forEach(cell=>{cell.addEventListener('pointerenter',()=>{const x=+cell.dataset.x,y=+cell.dataset.y;const coordinate=options.pixel?`像素 x[${x}], y[${y}]`:`角单元 H[${x}], V[${y}]`;$('spatialHover').textContent=`${coordinate} · 中心 (${fmt((xedges[x]+xedges[x+1])/2,3)}, ${fmt((yedges[y]+yedges[y+1])/2,3)}) ${options.pixel?'μm':'mrad'} · ${val(rows[y][x])}${options.density?' μm⁻²':options.pixel&&!options.percent?' 光子 / 发':''}`;});if(options.interactive){const choose=()=>{selectedH=+cell.dataset.x;selectedV=+cell.dataset.y;renderMapping();};cell.addEventListener('click',choose);cell.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});}});
}
function renderSpatial(){const o=data.optics;heatmap('txPlot',o.tx_energy_fraction,o.tx_h_edges_mrad,o.tx_v_edges_mrad,{percent:true});
 const scope=!IS_SCAN?data.spatial_scopes[$('spatialScope').value]:null;
 heatmap('sensorPlot',reshape(scope?scope.signal_photons_per_pixel:data.illumination.signal_photons_per_pixel_per_pulse,o.array_shape),data.x_edges_um,data.y_edges_um,{xLabel:'x · μm',yLabel:'y · μm',colorLabel:scope&&$('spatialScope').value==='slot'?'光子/slot':'光子/发',pixel:true,groups:$('showGroups').checked});
 if(scope){$('sensorScopeTitle').textContent='探测面入射光子 · '+scope.scope_label;$('sensorScopeUnit').textContent=scope.unit;$('spatialViewState').textContent=(viewIsAcquisition?'采集工况 · ':'参数预览 · ')+scope.scope_label+' · PDE / FF 前';}
}

function channelName(id){return `H${id%base.optics.channels_h} · V${Math.floor(id/base.optics.channels_h)}`;}
function renderPicker(){if(!IS_SCAN){channelLocator.setSelection(selectedChannels);$('channelInput').value=selectedChannels.join(', ');return;}$('channelPicker').style.gridTemplateColumns=`repeat(${base.optics.channels_h},minmax(0,1fr))`;$('channelPicker').innerHTML=data.histogram.counts.map((_,id)=>`<button class="${selectedChannels.includes(id)?'selected':''}" aria-pressed="${selectedChannels.includes(id)}" data-channel="${id}" title="通道 ${id}：${channelName(id)}">${channelName(id)} <span>/${id}</span></button>`).reverse().reduce((rows,html,i)=>{const row=Math.floor(i/base.optics.channels_h);(rows[row]??=[]).unshift(html);return rows;},[]).flat().join('');$('channelInput').value=selectedChannels.join(', ');}
function parseChannels(text){const count=data.histogram.counts.length,result=new Set();if(!text.trim())throw Error('请输入至少一个通道编号。');for(const term of text.split(/[,，]/)){const match=term.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!match)throw Error('格式示例：0, 2, 4-5。');const start=+match[1],end=match[2]===undefined?start:+match[2];if(start>end||end>=count)throw Error(`通道编号范围为 0–${count-1}，起点不能大于终点。`);for(let i=start;i<=end;i++)result.add(i);}if(result.size>catalog.algorithms.max_visible_channels)throw Error('同时显示通道超过 '+catalog.algorithms.max_visible_channels+'；请分批选择。');return [...result].sort((a,b)=>a-b);}
function canvasSetup(canvas){const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);return [ctx,rect.width,rect.height];}
function visibleSeries(){return Object.fromEntries([...document.querySelectorAll('[data-series]')].map(x=>[x.dataset.series,x.checked]));}
function histogramData(){return IS_SCAN?data:bHistogram?.view;}
function histMaximum(ch,range,series){return PhotonHistogram.maximum(histogramData(),ch,range,series);}
function drawHistogram(canvas,ch,range,ymax,series,overview=false){return PhotonHistogram.draw(canvas,histogramData(),ch,range,ymax,series,overview,windowRange);}
function updateHistogramLabels(){const shown=histogramData();if(!shown)return;
 for(const input of document.querySelectorAll('[data-series]')){const wasDisabled=input.disabled,available=input.dataset.series==='observed'||input.dataset.series==='ideal'&&!!shown.references||input.dataset.series==='noise'&&!!(shown.noise_reference||shown.statistics?.noise_mean)||input.dataset.series==='error'&&!!shown.statistics?.upper;input.disabled=!available;if(!available)input.checked=false;else if(wasDisabled)input.checked=true;}
 $('noiseReferenceLabel').textContent=shown.noise_reference?'理想噪声基线':'纯噪声输出均值';
 $('noiseReferenceExplanation').textContent=shown.noise_reference?'橙线是本视图曝光次数对应的理想噪声候选计数标量，未计 SPAD/TDC、首事件/符合/容量损失，不是混合记录中的噪声分量或检测阈值。按当前标准时间分箱宽度归一；末尾不足整宽的分箱也保持同一标量。':'若可用，橙线来自该次任务保存的关激光重复采集输出均值。';
 $('statisticsNote').textContent=(shown.statistics_note||(shown.statistics?`${shown.statistics.trial_count} 次含噪统计（包含首次；0表示无重复统计）`:'没有对应范围的重复统计。'))+' · '+(shown.noise_reference?'解析噪声基线，无额外采集':shown.statistics?.noise_mean?shown.statistics.noise_trial_count+' 次关激光参考':'该采集范围无噪声参考');
 $('histogramObservationExplanation').textContent=IS_SCAN?'采集范围由当前扫描选择决定。':shown.scope==='slot'?`蓝柱为第1轮完整采集的 ${shown.shots_in_view} 发 slot 累积。M次重复只用于误差棒，不叠加到蓝柱。`:`蓝柱仅为 G${shown.gate_index} 的真实记录；此任务没有逐gate重复统计，不绘制该范围误差棒。`;
 $('binNote').textContent=`显示分箱 ${shown.histogram.bin_ps} ps · 原始 TDC ${data.record_schema.tdc_bin_ps} ps`;
}
function renderHistograms(){
 const shown=histogramData();$('exportHistogram').disabled=!shown||(!IS_SCAN&&bHistogram.busy);
 if(!shown||(!IS_SCAN&&bHistogram.busy)){$('histogramPlots').innerHTML='<div class="hist-loading">'+(bHistogram?.busy?'正在读取所选范围；沿用已保存记录，不重新采集。':'当前范围尚无可显示数据。')+'</div>';return;}
 updateHistogramLabels();$('histogramPlots').classList.toggle('multi',selectedChannels.length>1);
 $('histogramPlots').innerHTML=selectedChannels.map(ch=>`<article class="hist-plot" data-scope="${shown.scope||'scan'}"><div class="hist-plot-head"><strong>CH ${String(ch).padStart(2,'0')} <span> / ${channelName(ch)}</span></strong><span>${fmt(shown.histogram.counts[ch].reduce((a,b)=>a+b,0),0)} 条记录</span></div>${!IS_SCAN?`<span class="hist-scope-badge">${esc(shown.scope_label)}</span>`:''}${shown.noise_reference?`<p class="field-note">理想噪声基线：${scientificLabel(shown.noise_reference.counts_per_bin[ch])} 计数 / 标准时间分箱（未计读出损失）</p>`:''}<canvas data-hist="${ch}" aria-label="通道 ${ch} ${shown.scope_label||''} 探测直方图"></canvas><div class="overview-chart-label"><span>ToF 全门概览 · 拖动窗口或边界</span><span class="window-key">橙色：当前观察窗口</span></div><canvas class="overview-canvas" data-overview="${ch}" aria-label="通道 ${ch} ToF 全门概览"></canvas><div class="local-window"><label>起点<input type="number" step="any" data-window-start="${ch}" aria-label="通道 ${ch} 观察窗口起点"></label><span>—</span><label>终点<input type="number" step="any" data-window-end="${ch}" aria-label="通道 ${ch} 观察窗口终点"></label><span>ns</span><button class="quiet small" data-window-apply="${ch}">应用</button></div><p class="window-note">精确时间输入 · 所选通道同步缩放</p>${shown.timeline?`<div class="exposure-timeline-label"><span>整个 slot · ${shown.timeline.grouped?'分组 gate 记录数':'逐 gate 记录数'}</span><span>右轴：门结束累计</span></div><canvas class="exposure-timeline" data-exposure="${ch}" aria-label="通道 ${ch} 整个slot的累积过程"></canvas><p class="field-note">${shown.timeline.grouped?'多个 gate 按组精确求和显示；':''}此图始终覆盖整个 slot，累计终点等于该通道 slot 总记录数。</p>`:''}</article>`).join('');
 const gate=[shown.histogram.edges_ns[0],shown.histogram.edges_ns.at(-1)];
 selectedChannels.forEach(ch=>{const canvas=document.querySelector(`[data-overview="${ch}"]`);PhotonHistogram.bindOverview(canvas,gate,()=>windowRange,range=>{windowRange=range;updateWindowInputs();redrawHistograms();});document.querySelector(`[data-window-apply="${ch}"]`).onclick=()=>{const lo=document.querySelector(`[data-window-start="${ch}"]`).valueAsNumber,hi=document.querySelector(`[data-window-end="${ch}"]`).valueAsNumber;if(!Number.isFinite(lo)||!Number.isFinite(hi)||lo>=hi||lo<gate[0]||hi>gate[1]){toast(`时间须在 ${gate[0]}–${gate[1]} ns 内，起点小于终点。`);return;}windowRange=[lo,hi];updateWindowInputs();redrawHistograms();};});
 $('histogramReferenceNote').textContent=shown.reference_note||'';updateWindowInputs();redrawHistograms();
}
function redrawHistograms(){const shown=histogramData();if(!shown||(!IS_SCAN&&bHistogram.busy))return;const series=visibleSeries(),shared=$('sharedScale').checked,axes=PhotonHistogram.scales(shown,selectedChannels,windowRange,series,shared),gate=[shown.histogram.edges_ns[0],shown.histogram.edges_ns.at(-1)];$('sharedScaleNote').textContent=shared?'全门固定：所选通道共用纵轴，拖动时间窗口不改变；切换 gate/slot、通道或图层后重新计算。':'局部自适应：各通道按当前窗口内可见图层缩放。';selectedChannels.forEach((ch,i)=>{drawHistogram(document.querySelector(`[data-hist="${ch}"]`),ch,windowRange,axes[i].max,series);drawHistogram(document.querySelector(`[data-overview="${ch}"]`),ch,gate,histMaximum(ch,gate,{observed:true}),series,true);if(shown.timeline)drawExposureTimeline(document.querySelector(`[data-exposure="${ch}"]`),shown.timeline,ch,shown.gate_index);});}
function updateWindowInputs(){const value=v=>Number(v.toPrecision(12)).toString();$('timeMin').value=value(windowRange[0]);$('timeMax').value=value(windowRange[1]);document.querySelectorAll('[data-window-start]').forEach(el=>el.value=value(windowRange[0]));document.querySelectorAll('[data-window-end]').forEach(el=>el.value=value(windowRange[1]));}
function renderMapping(){const o=data.optics,nx=o.tx_h_edges_mrad.length-1,idx=selectedV*nx+selectedH,x=o.angular_h_centers_mrad[idx],y=o.angular_v_centers_mrad[idx];$('angleH').value=String(selectedH);$('angleV').value=String(selectedV);$('angleLabel').innerHTML=`H[${selectedH}] · V[${selectedV}]<small>中心 (${fmt(x,3)}, ${fmt(y,3)}) mrad · 范围 H ${fmt(o.tx_h_edges_mrad[selectedH],2)}…${fmt(o.tx_h_edges_mrad[selectedH+1],2)} / V ${fmt(o.tx_v_edges_mrad[selectedV],2)}…${fmt(o.tx_v_edges_mrad[selectedV+1],2)}</small>`;heatmap('anglePlot',o.psf_capture_fraction,o.tx_h_edges_mrad,o.tx_v_edges_mrad,{percent:true,fixedMax:1,interactive:true,selected:[selectedH,selectedV]});heatmap('psfPlot',data.angle_psfs[idx],data.x_edges_um,data.y_edges_um,{pixel:true,percent:true,xLabel:'x · μm',yLabel:'y · μm',groups:true,height:510});const fractions=o.angle_to_channel_fraction[idx];$('captureValue').textContent=fmt(o.psf_capture_fraction[selectedV][selectedH]*100,2)+'%';$('channelFractions').innerHTML=fractions.map((v,ch)=>`<div class="share-row"><span>CH ${ch} · H${ch%base.optics.channels_h} V${Math.floor(ch/base.optics.channels_h)}</span><div class="share-track"><div class="share-fill" style="width:${v*100}%"></div></div><span class="share-value">${fmt(v*100,2)}%</span></div>`).join('');renderCrosstalk();}
function showConcept(key){const [title,text]=concepts[key];const note=key==='rx'?' 当前采集/显示映射：'+(base.optics.rx_model==='dataset'?'光学数据库':base.optics.mapping_mode==='inverted'?'倒置':'历史正向')+'。':'';$('overviewDetail').innerHTML=`<strong>${title}</strong><br>${text}${note}`;$('overviewDetail').classList.remove('hidden');$('toggleOverview').setAttribute('aria-expanded','true');$('toggleOverview').innerHTML='收起概念说明 <span>−</span>';document.querySelectorAll('[data-concept]').forEach(el=>el.classList.toggle('selected',el.dataset.concept===key));}
function describeValue(value){const text=typeof value==='object'?JSON.stringify(value):String(value);return text.length>300?text.slice(0,300)+'…（完整值见配置导出）':text;}
function showChanges(){const rows=changes();dialog('当前参数草稿',`<p>以下为本地界面草稿的改动。采集图仍对应原工况；参数可视化独立更新。</p>${rows.length?`<table><thead><tr><td>参数</td><td>参考工况</td><td>当前草稿</td></tr></thead><tbody>${rows.map(([p,n])=>`<tr><td>${n}</td><td>${esc(describeValue(get(lastResult?.form_configuration||defaultsForm,p)))}</td><td>${esc(describeValue(get(draft,p)))}</td></tr>`).join('')}</tbody></table>`:'<p>当前参数与参考工况一致。</p>'}`);}

function reshape(values,shape){return Array.from({length:shape[0]},(_,i)=>values.slice(i*shape[1],(i+1)*shape[1]));}
function setError(error){$('systemError').textContent=error.message||String(error);$('systemError').classList.remove('hidden');}
async function request(url,body,raw=false,signal){const response=await fetch(url,{cache:'no-store',signal,...(body===undefined?{}:{method:'POST',headers:{'Content-Type':raw?'text/plain':'application/json'},body:raw?body:JSON.stringify(body)})});const value=await response.json();if(!response.ok)throw Error(typeof value.detail==='string'?value.detail:JSON.stringify(value.detail||value));return value;}
function collect(){if(loadingConfig)throw Error('配置正在载入，请稍候。');const values=clone(draft);for(const el of document.querySelectorAll('#parameterGroups [data-path]')){let value;if(el.dataset.type==='json')value=JSON.parse(el.value);else if(el.type==='checkbox')value=el.checked;else if(el.type==='number'){if(el.value.trim()===''||!Number.isFinite(el.valueAsNumber))throw Error(el.getAttribute('aria-label')+'需要有限数值');value=el.valueAsNumber;}else value=el.value;set(values,el.dataset.path,value);}values.spectral_inputs=editors.values();return values;}
function canonical(values){const out={readout:clone(values.readout),spectral_inputs:clone(values.spectral_inputs)};for(const [old,path]of Object.entries(catalog.form_paths)){const value=get(values,old);if(value===undefined)throw Error('表单缺少 '+old);const [group,key]=path.split('.');(out[group]??={})[key]=value;}return out;}
function queuePreview(){renderReadoutLayoutSummary('pending');clearTimeout(previewTimer);previewSerial++;previewController?.abort();$('previewState').textContent='参数已改变，正在更新当前配置预览…';previewTimer=setTimeout(()=>refreshPreview().catch(setError),catalog.algorithms.parameter_preview_debounce_ms);}
async function refreshPreview(){const serial=++previewSerial;previewController?.abort();const controller=previewController=new AbortController();let cfg;try{cfg=canonical(collect());const next=await request(API+(IS_SCAN?'/workspace-preview':'/preview'),cfg,false,controller.signal);if(serial!==previewSerial)return;previewData=next;if(!IS_SCAN&&$('mechanismDataSource').value==='parameters')renderBMechanism();renderReadoutLayoutSummary();$('previewState').textContent='当前配置预览 · '+next.provenance.configuration_sha256.slice(0,12)+' · 尚未包含随机探测记录';renderParameterFigure();if(!lastResult||!viewIsAcquisition)showModel(next,false);else if(IS_SCAN)renderScanPreviewStatus(next);$('systemError').classList.add('hidden');}catch(error){if(error.name==='AbortError')return;renderReadoutLayoutSummary('invalid');$('previewState').textContent='预览未更新：当前输入未通过校验，不能将旧图当成新结果。';throw error;}}
function renderBMechanism(){const preview=$('mechanismDataSource').value==='parameters';const value=preview?previewData:data;if(value)bMechanism.setModel(value,!preview&&viewIsAcquisition);}
function attachMetadata(value){value.help=catalog.help;value.readout_modes=catalog.readout_modes;return value;}
function showModel(value,isResult){viewIsAcquisition=isResult;if(IS_SCAN&&isResult)value=scanDisplayModel(value);data=attachMetadata(value);base=value.form_configuration;const o=data.optics,b=o.budget,a=isResult?data.audit:null;
 if(!IS_SCAN){if(!isResult)bHistogram.cancel();if(isResult)$('mechanismDataSource').value='display';$('mechanismSourceStatus').textContent='';renderBMechanism();const c=data.acquisition_context;$('bScopeRules').innerHTML=`<p><strong>默认口径：</strong>光子空间图默认单发（图内可切换slot）；探测记录、损失、测距与直方图默认一次slot的 <b>N=${c.shots} 发累积</b>。<b>M=${c.trial_count===null?'未保存':c.trial_count}</b> 是独立统计重复，不能再叠加到蓝柱。</p><details><summary>各类图表的单位与统计范围</summary><div class="matrix-scroll"><table>${c.scope_rules.map(r=>`<tr><td>${esc(r.item)}</td><td>${esc(r.scope)}</td></tr>`).join('')}</table></div></details>`;}
 $('metrics').innerHTML=[[IS_SCAN&&isResult?'探测面信号 · 发射均值':'单发·探测面信号光子',IS_SCAN&&isResult?(data.display_summary.mean_sensor_photons_per_emitted_pulse===null?'—':fmt(data.display_summary.mean_sensor_photons_per_emitted_pulse,2)):fmt(b.signal_sensor_incident_photons_per_pulse,2),IS_SCAN?'光子 / 发 · PDE / FF 前':`光子 / 发 · PDE/FF前；N发完整回波共 ${fmt(data.acquisition_context.signal_sensor_photons_per_slot,2)} 光子（未裁门）`,true],[IS_SCAN?'最终探测记录':'slot·最终探测记录',a?fmt(a.final_records,0):'—',a?IS_SCAN?'完整扫描采集':`${base.timing.laser_shots} 发 · 首次完整采集`:'提交仿真后显示',false],[IS_SCAN?'SPAD 死时间损失':'slot·SPAD 死时间损失',a?fmt(a.spad_dead_losses,0):'—',IS_SCAN?'完整扫描采集统计':`${base.timing.laser_shots} 发累积，非 M 次统计相加`,false],[IS_SCAN?'TDC / 容量损失':'slot·TDC / 容量损失',a?fmt(a.tdc_dead_losses+a.capacity_losses,0):'—',IS_SCAN?'完整扫描采集统计':`${base.timing.laser_shots} 发累积，非 M 次统计相加`,false]].map(([label,val,note,accent])=>`<article class="metric"><p class="metric-label">${label}</p><p class="metric-number ${accent?'accent':''}">${val}</p><p class="metric-note">${note}</p></article>`).join('');
 $('sceneSummary').textContent=`${base.optics.range_m} m · ${base.optics.channels_h} × ${base.optics.channels_v} 通道 · ${IS_SCAN?'按扫描时序发射':base.timing.laser_shots+' 发'}`;
 document.querySelector('.overview-foot>span:last-child').textContent=data.optics.dataset.synthetic?'构造光学样例':'导入光学数据';
 $('spatialViewState').textContent=isResult?'采集工况 · PDE / FF 前':'当前参数预览 · PDE / FF 前';
 $('resultViewState').textContent=(isResult?'采集结果 '+(displayedJob||'')+' · ':'参数预览 · ')+data.provenance.configuration_sha256.slice(0,12)+(data.view_note?' · '+data.view_note:'');
 $('txCoverage').textContent=o.tx_energy_normalization?`域内归一化 · 份额合计 ${fmt(b.tx_angular_coverage_fraction*100,1)}%`:`历史结果 · 原角域覆盖 ${fmt(b.tx_angular_coverage_fraction*100,1)}%（重新运行采用域内归一化）`;$('arraySummary').textContent=`${o.array_shape[1]} × ${o.array_shape[0]} 像素 · ${base.optics.channels_h} × ${base.optics.channels_v} 通道`;
 $('histogramPanel').classList.toggle('hidden',!isResult);$('mappingPanel').classList.remove('hidden');$('crosstalkPanel').classList.remove('hidden');
 const nx=o.tx_h_edges_mrad.length-1,ny=o.tx_v_edges_mrad.length-1;selectedH=selectedH===undefined?Math.floor(nx/2):Math.min(nx-1,selectedH);selectedV=selectedV===undefined?Math.floor(ny/2):Math.min(ny-1,selectedV);
 $('angleH').innerHTML=Array.from({length:nx},(_,i)=>`<option value="${i}">${i}</option>`).join('');$('angleV').innerHTML=Array.from({length:ny},(_,i)=>`<option value="${i}">${i}</option>`).join('');
 bindExtraPanels();showFormula($('responseFormula'),data.formulas.b_response_matrix);renderSpatial();renderMapping();
 if(isResult){$('replayState').textContent='';selectedChannels=selectedChannels.filter(ch=>ch<data.histogram.counts.length);if(!selectedChannels.length)selectedChannels=[0];const gate=data.histogram.edges_ns;
   peakWindow=data.parameter_figures.timing.focus_window_ns||[gate[0],gate.at(-1)];windowRange=[...peakWindow];
   $('replayBin').value=data.record_schema.tdc_bin_ps;
   if(!IS_SCAN){channelLocator.setModel(data,displayedJob);bHistogram.setModel(data,displayedJob,selectedChannels);}renderPicker();renderHistograms();renderResultDetails();
 }
 $('auditContent').innerHTML=`<table>${[['入瞳信号光子 / 发',b.signal_rx_incident_photons_per_pulse],['探测面信号光子 / 发',b.signal_sensor_incident_photons_per_pulse],['理想候选雪崩 / 发',b.signal_candidate_avalanches_per_pulse],['能量守恒残差 / J',b.energy_balance_residual_j]].map(([k,v])=>`<tr><td>${k}</td><td>${scientificLabel(v)}</td></tr>`).join('')}</table><p class="field-note">${esc(data.provenance.scope)} · ${esc(data.provenance.utc)} · ${esc(data.provenance.model_version)}</p><pre>${esc(JSON.stringify({configuration:data.configuration,provenance:data.provenance,tx_energy_normalization:o.tx_energy_normalization||null,noise_reference:data.noise_reference||null,initialization:data.audit?.initialization||null,statistics:data.statistics?{trial_count:data.statistics.trial_count,noise_trial_count:data.statistics.noise_trial_count,method:data.statistics.method,note:data.statistics.note}:null,limitations:o.assumptions},null,2))}</pre>`;
 if(IS_SCAN)renderScanWorkspace(value,isResult);markChanges();renderReadoutLayoutSummary();
}
function renderResultDetails(){const root=$('rangesAndFlow');root.classList.remove('hidden');const ranges=data.channel_ranges;root.innerHTML='<h2>'+(IS_SCAN?'全采集混合角度诊断与计算过程':'slot 累积测距与光子预算')+'</h2>'+(ranges?`<p class="field-note">${IS_SCAN?'记录与测距对应当前扫描采集范围':'记录与测距来自首次完整采集的slot累积'}；光学预算按各行单位区分单发/单门/秒。未经专用检测门限判定，不声明 Pd/PFA。</p><div class="matrix-scroll"><table class="range-table"><thead><tr><th>通道</th><th>记录数</th><th>原始距离 / m</th><th>峰值评分</th></tr></thead><tbody>${ranges.rows.map(r=>`<tr><td>${channelName(r.channel)}</td><td>${r.recorded_counts}</td><td>${r.raw_distance_m===null?'—':fmt(r.raw_distance_m,4)}</td><td>${scientificLabel(r.peak_score)}</td></tr>`).join('')}</tbody></table></div>`:'');if(data.photon_flow){root.insertAdjacentHTML('beforeend',`<p class="field-note">${esc(data.photon_flow.intro)} 背景原始光子积分波段：${data.photon_flow.background_integration_band_nm.join('–')} nm。</p>`);for(const step of data.photon_flow.steps){const section=document.createElement('details');section.className='explanation';section.innerHTML=`<summary>${esc(step.title)}</summary><p>${esc(step.logic)}</p><div class="flow-formula"></div><p>${esc(step.symbols)}</p><table class="range-table">${step.values.map(v=>`<tr><td>${esc(v.label)}</td><td>${typeof v.value==='number'?scientificLabel(v.value):esc(v.value)}</td><td>${esc(v.unit)}</td></tr>`).join('')}</table>`;root.append(section);showFormula(section.querySelector('.flow-formula'),step.latex);}}}
async function loadJob(id,restoreForm=true){const result=await request('/api/jobs/'+id+(IS_SCAN?'/scan-view':'/system-view'));rawResult=clone(result);lastResult=result;displayedJob=id;if(restoreForm){previewSerial++;clearTimeout(previewTimer);previewController?.abort();draft=clone(result.form_configuration);localStorage.setItem(KEY,JSON.stringify(draft));data=attachMetadata(result);base=result.form_configuration;renderParameters();previewData=result;renderParameterFigure();$('previewState').textContent='已载入历史采集工况；参数图与该次配置对应。';}showModel(result,true);$('exportRawResult').disabled=false;history.replaceState(null,'',(IS_SCAN?'/system/scan':'/system')+'?job='+encodeURIComponent(id));}
async function refreshJobs(){clearTimeout(pollTimer);const jobs=(await request('/api/jobs')).filter(j=>j.kind===WORKSPACE_KIND);$('jobs').innerHTML=jobs.length?jobs.map(j=>`<div class="live-job"><span><strong>${esc(j.id.slice(0,8))} · ${esc(j.status)}</strong><small>${esc(j.message)}</small><progress value="${j.completed}" max="${j.total}"></progress></span>${j.status==='completed'?`<button class="quiet small" data-view-job="${j.id}">查看结果</button>`:''}${['running','queued'].includes(j.status)?`<button class="text-button" data-cancel-job="${j.id}">${j.cancel_requested?'取消中…':'取消'}</button>`:''}</div>`).join(''):'<p class="muted tiny">暂无 B 任务。</p>';
 const active=jobs.find(j=>j.id===currentJob);if(active){document.querySelector('.job-state').textContent=active.status+' · '+active.id.slice(0,8);$('jobSummary').textContent=active.message;if(active.status==='completed'&&displayedJob!==active.id){await loadJob(active.id,false);}if(['failed','cancelled','interrupted'].includes(active.status))setError(active.message);}
 if(jobs.some(j=>['queued','running'].includes(j.status)))pollTimer=setTimeout(()=>refreshJobs().catch(setError),catalog.algorithms.job_poll_ms);
}
async function importForm(config){const result=await request(API+'/form',config);draft=result.form;renderParameters();saveDraft();}
function selectDisplayChannels(channels){
 const next=[...new Set(channels)];
 if(!next.length||next.length>catalog.algorithms.max_visible_channels){toast('请选择至少一个通道，且不超过 '+catalog.algorithms.max_visible_channels+' 个。');return;}
 selectedChannels=next.sort((a,b)=>a-b);$('histError').classList.add('hidden');renderPicker();if(IS_SCAN){renderHistograms();drawScanResults();}else bHistogram.setChannels(selectedChannels);
}
function toggleDisplayChannel(ch){selectDisplayChannels(selectedChannels.includes(ch)?selectedChannels.filter(v=>v!==ch):[...selectedChannels,ch]);}
function bind(){
 if(!IS_SCAN){channelLocator=new PhotonChannelLocator($('channelLocator'),document.querySelector('.hist-controls .channel-control'),{onToggle:toggleDisplayChannel,onSelect:selectDisplayChannels});$('histogramTitle').textContent='通道分布与探测直方图';
 bMechanism=new BAcquisitionMechanism($('bMechanismPanel'));bHistogram=new BHistogramViews($('bHistogramControls'),{request,onExport:view=>download('b-'+view.scope+'-view.json',{configuration:data.configuration,provenance:data.provenance,view}),onError:e=>{$('histError').textContent=e.message;$('histError').classList.remove('hidden');},onChange:()=>{renderHistograms();if(bHistogram?.view)$('histError').classList.add('hidden');}});
 $('overviewTitle').textContent='模型原理与采集机制';$('overviewTabs').classList.remove('hidden');$('bScopeRules').classList.remove('hidden');$('spatialScopeControls').classList.remove('hidden');$('spatialScopeNote').classList.remove('hidden');
 const tabs=[...document.querySelectorAll('[data-overview-tab]')];for(const button of tabs){button.onclick=()=>{const mechanism=button.dataset.overviewTab==='mechanism';$('bMechanismPanel').classList.toggle('hidden',!mechanism);$('opticalOverviewPanel').classList.toggle('hidden',mechanism);$('toggleOverview').classList.toggle('hidden',mechanism);tabs.forEach(t=>{const active=t===button;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});};button.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const next=tabs[(tabs.indexOf(button)+1)%tabs.length];next.click();next.focus();}};}$('mechanismTab').click();$('spatialScope').onchange=renderSpatial;$('mechanismDataSource').onchange=async()=>{if($('mechanismDataSource').value==='parameters'){try{$('mechanismSourceStatus').textContent='正在更新参数预览…';await refreshPreview();$('mechanismSourceStatus').textContent='仅机制说明使用当前参数；下方采集结果仍属于标注的任务。';}catch(e){$('mechanismSourceStatus').textContent='机制预览未更新：'+e.message;}}else{$('mechanismSourceStatus').textContent='';renderBMechanism();}};
 }

 $('parameterGroups').addEventListener('change',async e=>{const el=e.target;if(el.matches('[data-path]')){try{draft=collect();updateVisibility();if(IS_SCAN)updateScanVisibility();saveDraft();}catch(error){setError(error);}return;}if(el.id==='importOpticalData'){try{const file=el.files[0];if(!file)return;const dataset=await request('/api/optics/validate',await file.text(),true);draft=collect();draft.optics.dataset=dataset;draft.optics.tx_model='dataset';draft.optics.rx_model='dataset';await importForm(canonical(draft));toast('已导入光学数据库；可以提交新采集。');}catch(error){setError(error);}}});
 $('parameterGroups').addEventListener('click',async e=>{if(e.target.closest('#exportOpticalData'))try{download('optical-dataset.json',await request(API+'/optical-data',canonical(collect())));}catch(error){setError(error);}});
 $('collapseAll').onclick=()=>document.querySelectorAll('.parameter-group,.parameter-group details').forEach(el=>el.open=false);$('expandAll').onclick=()=>document.querySelectorAll('.parameter-group,.parameter-group details').forEach(el=>el.open=true);
 $('resetDraft').onclick=async()=>{try{loadingConfig=true;$('runPreview').disabled=true;$('resetDraft').disabled=true;catalog=await request(API);defaultsForm=catalog.form_defaults;draft=clone(defaultsForm);renderParameters();loadingConfig=false;saveDraft();toast('已重新读取 YAML 默认值。');}catch(error){setError(error);}finally{loadingConfig=false;$('runPreview').disabled=false;$('resetDraft').disabled=false;}};
 $('runPreview').onclick=async()=>{try{$('runPreview').disabled=true;const config=await request(API+'/validate',canonical(collect()));if(IS_SCAN){const check=await request(API+'/workspace-preview',config);if(check.resource_probe.blocked)throw Error('当前背景候选至少 '+Math.ceil(check.resource_probe.expected_noise_candidates)+'，超过限额 '+check.resource_probe.event_limit+'。请调整工况、算法限额，或载入具名快速示例。');}draft=collect();localStorage.setItem(KEY,JSON.stringify(draft));const job=await request('/api/jobs',{kind:WORKSPACE_KIND,config});currentJob=job.id;$('jobHistory').classList.remove('hidden');$('resultViewState').textContent='任务运行中；下方仍为上次采集或参数预览。';$('systemError').classList.add('hidden');await refreshJobs();}catch(error){setError(error);}finally{$('runPreview').disabled=false;}};
 $('reviewChanges').onclick=showChanges;
 $('exportDraft').onclick=async()=>{try{const experiment=await request(API+'/validate',canonical(collect()));download('b-system-config.json',{schema_version:3,kind:WORKSPACE_KIND,experiment});}catch(error){setError(error);}};
 $('importConfiguration').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const value=await request(API+'/import',await file.text(),true);await importForm(value);}catch(error){setError(error);}};
 $('toScan').onclick=async()=>{try{const saved=localStorage.getItem('spad-columns-v4'),current=saved?JSON.parse(saved).experiment:{};const value=await request('/api/columns/from-system',{system:canonical(collect()),current});sessionStorage.setItem('lidar-system-to-columns',JSON.stringify(value));location.href='/system/scan';}catch(error){setError(error);}};
 $('exportRawResult').onclick=async()=>{try{download(displayedJob+'-original-result.json',await request('/api/jobs/'+displayedJob+'/result'));}catch(error){setError(error);}};
 $('showSources').onclick=()=>dialog('配置与数据来源',`<p>工况来自 YAML 默认值与用户覆盖。参数图由 Python 公共核心计算；采集记录来自保存了随机种子的事件仿真。</p><p>当前光学来源：${esc(data.optics.dataset.label)}。${data.optics.dataset.synthetic?'含构造数据，不代表实测光学系统。':''}</p><pre>${esc(JSON.stringify({configuration:data.configuration,provenance:data.provenance},null,2))}</pre>`);
 $('toggleOverview').onclick=()=>{if($('overviewDetail').classList.contains('hidden'))showConcept('rx');else{$('overviewDetail').classList.add('hidden');$('toggleOverview').setAttribute('aria-expanded','false');$('toggleOverview').innerHTML='概念与计算逻辑 <span>＋</span>';}};document.querySelectorAll('[data-concept]').forEach(el=>el.onclick=()=>showConcept(el.dataset.concept));
 $('toggleJobs').onclick=()=>{$('jobHistory').classList.toggle('hidden');refreshJobs().catch(setError);};$('jobs').onclick=async e=>{try{const view=e.target.closest('[data-view-job]'),cancel=e.target.closest('[data-cancel-job]');if(view){currentJob=view.dataset.viewJob;await loadJob(view.dataset.viewJob);}if(cancel){await request('/api/jobs/'+cancel.dataset.cancelJob+'/cancel',{});await refreshJobs();}}catch(error){setError(error);}};
 $('showGroups').onchange=renderSpatial;
 $('applyChannels').onclick=()=>{try{selectDisplayChannels(parseChannels($('channelInput').value));}catch(error){$('histError').textContent=error.message;$('histError').classList.remove('hidden');}};$('channelInput').onkeydown=e=>{if(e.key==='Enter')$('applyChannels').click();};
 $('channelPicker').onclick=e=>{const button=e.target.closest('[data-channel]');if(button)toggleDisplayChannel(+button.dataset.channel);};
 $('applyWindow').onclick=()=>{const lo=$('timeMin').valueAsNumber,hi=$('timeMax').valueAsNumber,gate=data.histogram.edges_ns;if(!Number.isFinite(lo)||!Number.isFinite(hi)||lo>=hi||lo<gate[0]||hi>gate.at(-1)){setError('时间窗口须位于接收门内，且起点小于终点。');return;}windowRange=[lo,hi];updateWindowInputs();redrawHistograms();};
 $('focusPeak').onclick=()=>{windowRange=[...peakWindow];updateWindowInputs();redrawHistograms();};$('showFullGate').onclick=()=>{windowRange=[data.histogram.edges_ns[0],data.histogram.edges_ns.at(-1)];updateWindowInputs();redrawHistograms();};$('sharedScale').onchange=renderHistograms;document.querySelectorAll('[data-series]').forEach(el=>el.onchange=renderHistograms);
 $('angleH').onchange=()=>{selectedH=+$('angleH').value;renderMapping();};$('angleV').onchange=()=>{selectedV=+$('angleV').value;renderMapping();};
 $('exportHistogram').onclick=()=>{const shown=histogramData();if(!shown||(!IS_SCAN&&bHistogram.busy))return;let csv='channel,time_ns,observed_counts,ideal_counts,'+(shown.noise_reference?'ideal_noise_reference_counts_per_bin':'noise_mean')+',sample_min,sample_max,scope,gate_index,accumulated_shots,processing_bin_ps\n';for(const ch of selectedChannels)shown.histogram.time_ns.forEach((t,i)=>{csv+=[ch,t,shown.histogram.counts[ch][i],shown.references?.[ch]?.counts[i]??'',shown.noise_reference?.counts_per_bin[ch]??shown.statistics?.noise_mean?.[ch]?.[i]??'',shown.statistics?.lower?.[ch]?.[i]??'',shown.statistics?.upper?.[ch]?.[i]??'',shown.scope||'scan',shown.gate_index??'',shown.shots_in_view??'',shown.histogram.bin_ps].join(',')+'\n';});download('b-'+(shown.scope||'scan')+'-histograms.csv',csv);};
 $('exportMapping').onclick=()=>{const idx=selectedAngleIndex();download('b-angle-response.json',{h_index:selectedH,v_index:selectedV,pixel_fractions:data.angle_psfs[idx],channel_fractions:data.optics.angle_to_channel_fraction[idx],configuration_sha256:data.provenance.configuration_sha256});};
 $('replayRecords').onclick=async()=>{if(IS_SCAN){await replayScanWorkspace();return;}$('replayRecords').disabled=true;try{const updated=await bHistogram.setBin($('replayBin').valueAsNumber);$('replayState').textContent=updated?'已按当前采集范围重放；原始记录未改动。':'分箱未更新。';}finally{$('replayRecords').disabled=false;}};
 $('closeDialog').onclick=$('dialogDone').onclick=()=>$('previewDialog').close();let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(()=>{if(viewIsAcquisition&&data.histogram)redrawHistograms();renderParameterFigure();if(IS_SCAN)drawScanResults();},100);});
}
async function init(){if(IS_SCAN)bootScanWorkspace();catalog=await request(API);defaultsForm=catalog.form_defaults;draft=clone(defaultsForm);
 const stored=localStorage.getItem(KEY)||localStorage.getItem('lidar-experiment-v2-'+WORKSPACE_KIND);if(stored){try{const parsed=JSON.parse(stored);const value=await request(API+'/form',parsed.experiment||parsed);draft=value.form;}catch(error){setError('旧草稿未载入：'+error.message);}}
 if(IS_SCAN&&sessionStorage.getItem('lidar-system-to-scan')){const transfer=JSON.parse(sessionStorage.getItem('lidar-system-to-scan'));const resolved=await request(API+'/form',transfer.experiment);draft=resolved.form;sessionStorage.removeItem('lidar-system-to-scan');}
 if(!IS_SCAN&&sessionStorage.getItem('lidar-budget-to-system')){const transfer=JSON.parse(sessionStorage.getItem('lidar-budget-to-system'));const resolved=await request(API+'/form',transfer.experiment);draft=resolved.form;sessionStorage.removeItem('lidar-budget-to-system');localStorage.setItem(KEY,JSON.stringify(draft));}
 previewData=await request(API+(IS_SCAN?'/workspace-preview':'/preview'),canonical(draft));data=attachMetadata(previewData);base=previewData.form_configuration;renderParameters();bind();if(IS_SCAN)bindScanWorkspace();showModel(data,false);$('previewState').textContent='当前配置预览 · '+previewData.provenance.configuration_sha256.slice(0,12);
 const job=new URLSearchParams(location.search).get('job');if(job){await loadJob(job);currentJob=job;}await refreshJobs();document.body.dataset.ready='true';
}
init().catch(error=>{$('loadingError').textContent='平台加载失败\n'+error.message;$('loadingError').classList.remove('hidden');console.error(error);});
